// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "conv2.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic conv2::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic conv2::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<18> conv2::ap_ST_fsm_state1 = "1";
const sc_lv<18> conv2::ap_ST_fsm_state2 = "10";
const sc_lv<18> conv2::ap_ST_fsm_state3 = "100";
const sc_lv<18> conv2::ap_ST_fsm_state4 = "1000";
const sc_lv<18> conv2::ap_ST_fsm_state5 = "10000";
const sc_lv<18> conv2::ap_ST_fsm_state6 = "100000";
const sc_lv<18> conv2::ap_ST_fsm_state7 = "1000000";
const sc_lv<18> conv2::ap_ST_fsm_state8 = "10000000";
const sc_lv<18> conv2::ap_ST_fsm_state9 = "100000000";
const sc_lv<18> conv2::ap_ST_fsm_state10 = "1000000000";
const sc_lv<18> conv2::ap_ST_fsm_state11 = "10000000000";
const sc_lv<18> conv2::ap_ST_fsm_state12 = "100000000000";
const sc_lv<18> conv2::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<18> conv2::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<18> conv2::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<18> conv2::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<18> conv2::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<18> conv2::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<32> conv2::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> conv2::ap_const_lv32_1 = "1";
const sc_lv<1> conv2::ap_const_lv1_0 = "0";
const sc_lv<32> conv2::ap_const_lv32_2 = "10";
const sc_lv<32> conv2::ap_const_lv32_3 = "11";
const sc_lv<32> conv2::ap_const_lv32_4 = "100";
const sc_lv<32> conv2::ap_const_lv32_5 = "101";
const sc_lv<32> conv2::ap_const_lv32_6 = "110";
const sc_lv<32> conv2::ap_const_lv32_7 = "111";
const sc_lv<32> conv2::ap_const_lv32_8 = "1000";
const sc_lv<32> conv2::ap_const_lv32_9 = "1001";
const sc_lv<32> conv2::ap_const_lv32_B = "1011";
const sc_lv<32> conv2::ap_const_lv32_C = "1100";
const sc_lv<32> conv2::ap_const_lv32_D = "1101";
const sc_lv<32> conv2::ap_const_lv32_E = "1110";
const sc_lv<4> conv2::ap_const_lv4_0 = "0000";
const sc_lv<1> conv2::ap_const_lv1_1 = "1";
const sc_lv<3> conv2::ap_const_lv3_0 = "000";
const sc_lv<2> conv2::ap_const_lv2_0 = "00";
const sc_lv<32> conv2::ap_const_lv32_A = "1010";
const sc_lv<32> conv2::ap_const_lv32_11 = "10001";
const sc_lv<32> conv2::ap_const_lv32_F = "1111";
const sc_lv<32> conv2::ap_const_lv32_10 = "10000";
const sc_lv<16> conv2::ap_const_lv16_0 = "0000000000000000";
const sc_lv<4> conv2::ap_const_lv4_A = "1010";
const sc_lv<4> conv2::ap_const_lv4_1 = "1";
const sc_lv<3> conv2::ap_const_lv3_5 = "101";
const sc_lv<3> conv2::ap_const_lv3_1 = "1";
const sc_lv<2> conv2::ap_const_lv2_2 = "10";
const sc_lv<2> conv2::ap_const_lv2_1 = "1";
const sc_lv<4> conv2::ap_const_lv4_8 = "1000";
const sc_lv<3> conv2::ap_const_lv3_6 = "110";
const sc_lv<10> conv2::ap_const_lv10_0 = "0000000000";
const sc_lv<32> conv2::ap_const_lv32_19 = "11001";
const bool conv2::ap_const_boolean_1 = true;

conv2::conv2(sc_module_name name) : sc_module(name), mVcdFile(0) {
    K2_W_V_U = new conv2_K2_W_V("K2_W_V_U");
    K2_W_V_U->clk(ap_clk);
    K2_W_V_U->reset(ap_rst);
    K2_W_V_U->address0(K2_W_V_address0);
    K2_W_V_U->ce0(K2_W_V_ce0);
    K2_W_V_U->q0(K2_W_V_q0);
    K2_B_V_U = new conv2_K2_B_V("K2_B_V_U");
    K2_B_V_U->clk(ap_clk);
    K2_B_V_U->reset(ap_rst);
    K2_B_V_U->address0(K2_B_V_address0);
    K2_B_V_U->ce0(K2_B_V_ce0);
    K2_B_V_U->q0(K2_B_V_q0);
    lenet_mac_muladd_dEe_U11 = new lenet_mac_muladd_dEe<1,1,9,16,26,26>("lenet_mac_muladd_dEe_U11");
    lenet_mac_muladd_dEe_U11->din0(K2_W_V_q0);
    lenet_mac_muladd_dEe_U11->din1(P1_out_V_q0);
    lenet_mac_muladd_dEe_U11->din2(grp_fu_830_p2);
    lenet_mac_muladd_dEe_U11->dout(grp_fu_830_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_K2_B_V_address0);
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( zext_ln106_fu_782_p1 );

    SC_METHOD(thread_K2_B_V_ce0);
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_K2_W_V_address0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( zext_ln1117_11_fu_645_p1 );

    SC_METHOD(thread_K2_W_V_ce0);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_P1_out_V_address0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( zext_ln1116_7_fu_649_p1 );

    SC_METHOD(thread_P1_out_V_ce0);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_add_ln106_fu_777_p2);
    sensitive << ( shl_ln_reg_1000 );
    sensitive << ( k4_0_reg_275 );

    SC_METHOD(thread_add_ln1116_3_fu_640_p2);
    sensitive << ( sub_ln1116_1_reg_891 );
    sensitive << ( zext_ln1117_9_fu_573_p1 );

    SC_METHOD(thread_add_ln1116_fu_435_p2);
    sensitive << ( sext_ln1116_reg_873 );
    sensitive << ( zext_ln1116_6_fu_431_p1 );

    SC_METHOD(thread_add_ln1117_5_fu_602_p2);
    sensitive << ( sext_ln1117_2_fu_586_p1 );
    sensitive << ( sext_ln1117_3_fu_598_p1 );

    SC_METHOD(thread_add_ln1117_6_fu_608_p2);
    sensitive << ( zext_ln89_reg_878 );
    sensitive << ( add_ln1117_5_fu_602_p2 );

    SC_METHOD(thread_add_ln1117_7_fu_629_p2);
    sensitive << ( trunc_ln1117_fu_613_p1 );
    sensitive << ( p_shl8_cast_fu_621_p3 );

    SC_METHOD(thread_add_ln1117_8_fu_635_p2);
    sensitive << ( zext_ln83_reg_896 );
    sensitive << ( add_ln1117_7_fu_629_p2 );

    SC_METHOD(thread_add_ln1117_fu_581_p2);
    sensitive << ( sext_ln1117_reg_922 );
    sensitive << ( zext_ln1117_10_fu_577_p1 );

    SC_METHOD(thread_add_ln1265_1_fu_714_p2);
    sensitive << ( zext_ln1265_3_fu_710_p1 );
    sensitive << ( zext_ln1265_2_fu_698_p1 );

    SC_METHOD(thread_add_ln1265_2_fu_344_p2);
    sensitive << ( add_ln1265_reg_847 );
    sensitive << ( zext_ln1265_4_fu_340_p1 );

    SC_METHOD(thread_add_ln1265_3_fu_736_p2);
    sensitive << ( add_ln1265_1_reg_973 );
    sensitive << ( zext_ln1265_5_fu_732_p1 );

    SC_METHOD(thread_add_ln1265_fu_322_p2);
    sensitive << ( zext_ln1265_1_fu_318_p1 );
    sensitive << ( zext_ln1265_fu_306_p1 );

    SC_METHOD(thread_add_ln703_fu_815_p2);
    sensitive << ( out_V_q0 );
    sensitive << ( sext_ln1265_fu_811_p1 );

    SC_METHOD(thread_add_ln89_1_fu_425_p2);
    sensitive << ( j_0_reg_175 );
    sensitive << ( zext_ln81_fu_409_p1 );

    SC_METHOD(thread_add_ln89_2_fu_510_p2);
    sensitive << ( shl_ln3_reg_909 );
    sensitive << ( k_0_reg_220 );

    SC_METHOD(thread_add_ln89_fu_365_p2);
    sensitive << ( i_0_reg_163 );
    sensitive << ( zext_ln79_fu_349_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( icmp_ln98_fu_678_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( icmp_ln98_fu_678_p2 );

    SC_METHOD(thread_c_fu_567_p2);
    sensitive << ( c_0_reg_231 );

    SC_METHOD(thread_grp_fu_830_p2);
    sensitive << ( out_V_q0 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_i_5_fu_684_p2);
    sensitive << ( i1_0_reg_242 );

    SC_METHOD(thread_i_fu_292_p2);
    sensitive << ( i_0_reg_163 );

    SC_METHOD(thread_icmp_ln100_fu_720_p2);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( j2_0_reg_253 );

    SC_METHOD(thread_icmp_ln102_fu_741_p2);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( set3_0_reg_264 );

    SC_METHOD(thread_icmp_ln104_fu_765_p2);
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( k4_0_reg_275 );

    SC_METHOD(thread_icmp_ln75_fu_286_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_163 );

    SC_METHOD(thread_icmp_ln77_fu_328_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( j_0_reg_175 );

    SC_METHOD(thread_icmp_ln79_fu_353_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( x_0_reg_187 );

    SC_METHOD(thread_icmp_ln81_fu_413_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( y_0_reg_198 );

    SC_METHOD(thread_icmp_ln83_fu_474_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( set_0_reg_209 );

    SC_METHOD(thread_icmp_ln85_fu_498_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( k_0_reg_220 );

    SC_METHOD(thread_icmp_ln87_fu_561_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( c_0_reg_231 );

    SC_METHOD(thread_icmp_ln98_fu_678_p2);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( i1_0_reg_242 );

    SC_METHOD(thread_j_1_fu_726_p2);
    sensitive << ( j2_0_reg_253 );

    SC_METHOD(thread_j_fu_334_p2);
    sensitive << ( j_0_reg_175 );

    SC_METHOD(thread_k_1_fu_504_p2);
    sensitive << ( k_0_reg_220 );

    SC_METHOD(thread_k_fu_771_p2);
    sensitive << ( k4_0_reg_275 );

    SC_METHOD(thread_out_V_address0);
    sensitive << ( out_V_addr_4_reg_927 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( out_V_addr_reg_1013 );
    sensitive << ( out_V_addr_3_reg_1023 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( zext_ln1265_6_fu_794_p1 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_out_V_ce0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_out_V_d0);
    sensitive << ( trunc_ln_reg_960 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( add_ln703_fu_815_p2 );

    SC_METHOD(thread_out_V_we0);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( tmp_16_fu_822_p3 );

    SC_METHOD(thread_p_shl4_cast_fu_444_p3);
    sensitive << ( trunc_ln1116_fu_440_p1 );

    SC_METHOD(thread_p_shl8_cast_fu_621_p3);
    sensitive << ( trunc_ln1117_2_fu_617_p1 );

    SC_METHOD(thread_set_1_fu_480_p2);
    sensitive << ( set_0_reg_209 );

    SC_METHOD(thread_set_fu_747_p2);
    sensitive << ( set3_0_reg_264 );

    SC_METHOD(thread_sext_ln1116_1_fu_460_p1);
    sensitive << ( tmp_13_fu_452_p3 );

    SC_METHOD(thread_sext_ln1116_fu_401_p1);
    sensitive << ( sub_ln1116_fu_395_p2 );

    SC_METHOD(thread_sext_ln1117_2_fu_586_p1);
    sensitive << ( add_ln1117_fu_581_p2 );

    SC_METHOD(thread_sext_ln1117_3_fu_598_p1);
    sensitive << ( tmp_18_fu_590_p3 );

    SC_METHOD(thread_sext_ln1117_fu_545_p1);
    sensitive << ( sub_ln1117_fu_539_p2 );

    SC_METHOD(thread_sext_ln1265_fu_811_p1);
    sensitive << ( K2_B_V_q0 );

    SC_METHOD(thread_shl_ln3_fu_490_p3);
    sensitive << ( trunc_ln89_fu_486_p1 );

    SC_METHOD(thread_shl_ln_fu_757_p3);
    sensitive << ( trunc_ln106_fu_753_p1 );

    SC_METHOD(thread_sub_ln1116_1_fu_464_p2);
    sensitive << ( p_shl4_cast_fu_444_p3 );
    sensitive << ( sext_ln1116_1_fu_460_p1 );

    SC_METHOD(thread_sub_ln1116_fu_395_p2);
    sensitive << ( zext_ln1116_fu_379_p1 );
    sensitive << ( zext_ln1116_5_fu_391_p1 );

    SC_METHOD(thread_sub_ln1117_fu_539_p2);
    sensitive << ( zext_ln1117_fu_523_p1 );
    sensitive << ( zext_ln1117_8_fu_535_p1 );

    SC_METHOD(thread_tmp_10_fu_515_p3);
    sensitive << ( add_ln89_2_fu_510_p2 );

    SC_METHOD(thread_tmp_11_fu_527_p3);
    sensitive << ( add_ln89_2_fu_510_p2 );

    SC_METHOD(thread_tmp_13_fu_452_p3);
    sensitive << ( add_ln1116_fu_435_p2 );

    SC_METHOD(thread_tmp_14_fu_787_p3);
    sensitive << ( add_ln1265_3_reg_986 );
    sensitive << ( add_ln106_fu_777_p2 );

    SC_METHOD(thread_tmp_15_fu_799_p3);
    sensitive << ( add_ln1265_3_reg_986 );
    sensitive << ( k4_0_reg_275 );

    SC_METHOD(thread_tmp_16_fu_822_p3);
    sensitive << ( out_V_q0 );

    SC_METHOD(thread_tmp_17_fu_549_p3);
    sensitive << ( add_ln1265_2_reg_860 );
    sensitive << ( add_ln89_2_fu_510_p2 );

    SC_METHOD(thread_tmp_18_fu_590_p3);
    sensitive << ( add_ln1117_fu_581_p2 );

    SC_METHOD(thread_tmp_3_fu_310_p3);
    sensitive << ( i_0_reg_163 );

    SC_METHOD(thread_tmp_4_fu_690_p3);
    sensitive << ( i1_0_reg_242 );

    SC_METHOD(thread_tmp_5_fu_702_p3);
    sensitive << ( i1_0_reg_242 );

    SC_METHOD(thread_tmp_6_fu_371_p3);
    sensitive << ( add_ln89_fu_365_p2 );

    SC_METHOD(thread_tmp_9_fu_383_p3);
    sensitive << ( add_ln89_fu_365_p2 );

    SC_METHOD(thread_tmp_s_fu_298_p3);
    sensitive << ( i_0_reg_163 );

    SC_METHOD(thread_trunc_ln106_fu_753_p1);
    sensitive << ( set3_0_reg_264 );

    SC_METHOD(thread_trunc_ln1116_fu_440_p1);
    sensitive << ( add_ln1116_fu_435_p2 );

    SC_METHOD(thread_trunc_ln1117_2_fu_617_p1);
    sensitive << ( add_ln1117_6_fu_608_p2 );

    SC_METHOD(thread_trunc_ln1117_fu_613_p1);
    sensitive << ( add_ln1117_6_fu_608_p2 );

    SC_METHOD(thread_trunc_ln89_fu_486_p1);
    sensitive << ( set_0_reg_209 );

    SC_METHOD(thread_x_fu_359_p2);
    sensitive << ( x_0_reg_187 );

    SC_METHOD(thread_y_fu_419_p2);
    sensitive << ( y_0_reg_198 );

    SC_METHOD(thread_zext_ln106_fu_782_p1);
    sensitive << ( add_ln106_fu_777_p2 );

    SC_METHOD(thread_zext_ln1116_5_fu_391_p1);
    sensitive << ( tmp_9_fu_383_p3 );

    SC_METHOD(thread_zext_ln1116_6_fu_431_p1);
    sensitive << ( add_ln89_1_fu_425_p2 );

    SC_METHOD(thread_zext_ln1116_7_fu_649_p1);
    sensitive << ( add_ln1116_3_reg_945 );

    SC_METHOD(thread_zext_ln1116_fu_379_p1);
    sensitive << ( tmp_6_fu_371_p3 );

    SC_METHOD(thread_zext_ln1117_10_fu_577_p1);
    sensitive << ( c_0_reg_231 );

    SC_METHOD(thread_zext_ln1117_11_fu_645_p1);
    sensitive << ( add_ln1117_8_reg_940 );

    SC_METHOD(thread_zext_ln1117_8_fu_535_p1);
    sensitive << ( tmp_11_fu_527_p3 );

    SC_METHOD(thread_zext_ln1117_9_fu_573_p1);
    sensitive << ( c_0_reg_231 );

    SC_METHOD(thread_zext_ln1117_fu_523_p1);
    sensitive << ( tmp_10_fu_515_p3 );

    SC_METHOD(thread_zext_ln1265_1_fu_318_p1);
    sensitive << ( tmp_3_fu_310_p3 );

    SC_METHOD(thread_zext_ln1265_2_fu_698_p1);
    sensitive << ( tmp_4_fu_690_p3 );

    SC_METHOD(thread_zext_ln1265_3_fu_710_p1);
    sensitive << ( tmp_5_fu_702_p3 );

    SC_METHOD(thread_zext_ln1265_4_fu_340_p1);
    sensitive << ( j_0_reg_175 );

    SC_METHOD(thread_zext_ln1265_5_fu_732_p1);
    sensitive << ( j2_0_reg_253 );

    SC_METHOD(thread_zext_ln1265_6_fu_794_p1);
    sensitive << ( tmp_14_fu_787_p3 );

    SC_METHOD(thread_zext_ln1265_7_fu_556_p1);
    sensitive << ( tmp_17_fu_549_p3 );

    SC_METHOD(thread_zext_ln1265_fu_306_p1);
    sensitive << ( tmp_s_fu_298_p3 );

    SC_METHOD(thread_zext_ln1495_fu_806_p1);
    sensitive << ( tmp_15_fu_799_p3 );

    SC_METHOD(thread_zext_ln79_fu_349_p1);
    sensitive << ( x_0_reg_187 );

    SC_METHOD(thread_zext_ln81_fu_409_p1);
    sensitive << ( y_0_reg_198 );

    SC_METHOD(thread_zext_ln83_fu_470_p1);
    sensitive << ( y_0_reg_198 );

    SC_METHOD(thread_zext_ln89_fu_405_p1);
    sensitive << ( x_0_reg_187 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln75_fu_286_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln77_fu_328_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln79_fu_353_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln81_fu_413_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln83_fu_474_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln85_fu_498_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln87_fu_561_p2 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( icmp_ln98_fu_678_p2 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( icmp_ln100_fu_720_p2 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( icmp_ln102_fu_741_p2 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( icmp_ln104_fu_765_p2 );

    ap_CS_fsm = "000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "conv2_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, out_V_address0, "(port)out_V_address0");
    sc_trace(mVcdFile, out_V_ce0, "(port)out_V_ce0");
    sc_trace(mVcdFile, out_V_we0, "(port)out_V_we0");
    sc_trace(mVcdFile, out_V_d0, "(port)out_V_d0");
    sc_trace(mVcdFile, out_V_q0, "(port)out_V_q0");
    sc_trace(mVcdFile, P1_out_V_address0, "(port)P1_out_V_address0");
    sc_trace(mVcdFile, P1_out_V_ce0, "(port)P1_out_V_ce0");
    sc_trace(mVcdFile, P1_out_V_q0, "(port)P1_out_V_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, K2_W_V_address0, "K2_W_V_address0");
    sc_trace(mVcdFile, K2_W_V_ce0, "K2_W_V_ce0");
    sc_trace(mVcdFile, K2_W_V_q0, "K2_W_V_q0");
    sc_trace(mVcdFile, K2_B_V_address0, "K2_B_V_address0");
    sc_trace(mVcdFile, K2_B_V_ce0, "K2_B_V_ce0");
    sc_trace(mVcdFile, K2_B_V_q0, "K2_B_V_q0");
    sc_trace(mVcdFile, i_fu_292_p2, "i_fu_292_p2");
    sc_trace(mVcdFile, i_reg_842, "i_reg_842");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, add_ln1265_fu_322_p2, "add_ln1265_fu_322_p2");
    sc_trace(mVcdFile, add_ln1265_reg_847, "add_ln1265_reg_847");
    sc_trace(mVcdFile, icmp_ln75_fu_286_p2, "icmp_ln75_fu_286_p2");
    sc_trace(mVcdFile, j_fu_334_p2, "j_fu_334_p2");
    sc_trace(mVcdFile, j_reg_855, "j_reg_855");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, add_ln1265_2_fu_344_p2, "add_ln1265_2_fu_344_p2");
    sc_trace(mVcdFile, add_ln1265_2_reg_860, "add_ln1265_2_reg_860");
    sc_trace(mVcdFile, icmp_ln77_fu_328_p2, "icmp_ln77_fu_328_p2");
    sc_trace(mVcdFile, x_fu_359_p2, "x_fu_359_p2");
    sc_trace(mVcdFile, x_reg_868, "x_reg_868");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, sext_ln1116_fu_401_p1, "sext_ln1116_fu_401_p1");
    sc_trace(mVcdFile, sext_ln1116_reg_873, "sext_ln1116_reg_873");
    sc_trace(mVcdFile, icmp_ln79_fu_353_p2, "icmp_ln79_fu_353_p2");
    sc_trace(mVcdFile, zext_ln89_fu_405_p1, "zext_ln89_fu_405_p1");
    sc_trace(mVcdFile, zext_ln89_reg_878, "zext_ln89_reg_878");
    sc_trace(mVcdFile, y_fu_419_p2, "y_fu_419_p2");
    sc_trace(mVcdFile, y_reg_886, "y_reg_886");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, sub_ln1116_1_fu_464_p2, "sub_ln1116_1_fu_464_p2");
    sc_trace(mVcdFile, sub_ln1116_1_reg_891, "sub_ln1116_1_reg_891");
    sc_trace(mVcdFile, icmp_ln81_fu_413_p2, "icmp_ln81_fu_413_p2");
    sc_trace(mVcdFile, zext_ln83_fu_470_p1, "zext_ln83_fu_470_p1");
    sc_trace(mVcdFile, zext_ln83_reg_896, "zext_ln83_reg_896");
    sc_trace(mVcdFile, set_1_fu_480_p2, "set_1_fu_480_p2");
    sc_trace(mVcdFile, set_1_reg_904, "set_1_reg_904");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, shl_ln3_fu_490_p3, "shl_ln3_fu_490_p3");
    sc_trace(mVcdFile, shl_ln3_reg_909, "shl_ln3_reg_909");
    sc_trace(mVcdFile, icmp_ln83_fu_474_p2, "icmp_ln83_fu_474_p2");
    sc_trace(mVcdFile, k_1_fu_504_p2, "k_1_fu_504_p2");
    sc_trace(mVcdFile, k_1_reg_917, "k_1_reg_917");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, sext_ln1117_fu_545_p1, "sext_ln1117_fu_545_p1");
    sc_trace(mVcdFile, sext_ln1117_reg_922, "sext_ln1117_reg_922");
    sc_trace(mVcdFile, icmp_ln85_fu_498_p2, "icmp_ln85_fu_498_p2");
    sc_trace(mVcdFile, out_V_addr_4_reg_927, "out_V_addr_4_reg_927");
    sc_trace(mVcdFile, c_fu_567_p2, "c_fu_567_p2");
    sc_trace(mVcdFile, c_reg_935, "c_reg_935");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, add_ln1117_8_fu_635_p2, "add_ln1117_8_fu_635_p2");
    sc_trace(mVcdFile, add_ln1117_8_reg_940, "add_ln1117_8_reg_940");
    sc_trace(mVcdFile, icmp_ln87_fu_561_p2, "icmp_ln87_fu_561_p2");
    sc_trace(mVcdFile, add_ln1116_3_fu_640_p2, "add_ln1116_3_fu_640_p2");
    sc_trace(mVcdFile, add_ln1116_3_reg_945, "add_ln1116_3_reg_945");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, trunc_ln_reg_960, "trunc_ln_reg_960");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, i_5_fu_684_p2, "i_5_fu_684_p2");
    sc_trace(mVcdFile, i_5_reg_968, "i_5_reg_968");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, add_ln1265_1_fu_714_p2, "add_ln1265_1_fu_714_p2");
    sc_trace(mVcdFile, add_ln1265_1_reg_973, "add_ln1265_1_reg_973");
    sc_trace(mVcdFile, icmp_ln98_fu_678_p2, "icmp_ln98_fu_678_p2");
    sc_trace(mVcdFile, j_1_fu_726_p2, "j_1_fu_726_p2");
    sc_trace(mVcdFile, j_1_reg_981, "j_1_reg_981");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, add_ln1265_3_fu_736_p2, "add_ln1265_3_fu_736_p2");
    sc_trace(mVcdFile, add_ln1265_3_reg_986, "add_ln1265_3_reg_986");
    sc_trace(mVcdFile, icmp_ln100_fu_720_p2, "icmp_ln100_fu_720_p2");
    sc_trace(mVcdFile, set_fu_747_p2, "set_fu_747_p2");
    sc_trace(mVcdFile, set_reg_995, "set_reg_995");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, shl_ln_fu_757_p3, "shl_ln_fu_757_p3");
    sc_trace(mVcdFile, shl_ln_reg_1000, "shl_ln_reg_1000");
    sc_trace(mVcdFile, icmp_ln102_fu_741_p2, "icmp_ln102_fu_741_p2");
    sc_trace(mVcdFile, k_fu_771_p2, "k_fu_771_p2");
    sc_trace(mVcdFile, k_reg_1008, "k_reg_1008");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, out_V_addr_reg_1013, "out_V_addr_reg_1013");
    sc_trace(mVcdFile, icmp_ln104_fu_765_p2, "icmp_ln104_fu_765_p2");
    sc_trace(mVcdFile, out_V_addr_3_reg_1023, "out_V_addr_3_reg_1023");
    sc_trace(mVcdFile, i_0_reg_163, "i_0_reg_163");
    sc_trace(mVcdFile, j_0_reg_175, "j_0_reg_175");
    sc_trace(mVcdFile, x_0_reg_187, "x_0_reg_187");
    sc_trace(mVcdFile, y_0_reg_198, "y_0_reg_198");
    sc_trace(mVcdFile, set_0_reg_209, "set_0_reg_209");
    sc_trace(mVcdFile, k_0_reg_220, "k_0_reg_220");
    sc_trace(mVcdFile, c_0_reg_231, "c_0_reg_231");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, i1_0_reg_242, "i1_0_reg_242");
    sc_trace(mVcdFile, j2_0_reg_253, "j2_0_reg_253");
    sc_trace(mVcdFile, set3_0_reg_264, "set3_0_reg_264");
    sc_trace(mVcdFile, k4_0_reg_275, "k4_0_reg_275");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, zext_ln1265_7_fu_556_p1, "zext_ln1265_7_fu_556_p1");
    sc_trace(mVcdFile, zext_ln1117_11_fu_645_p1, "zext_ln1117_11_fu_645_p1");
    sc_trace(mVcdFile, zext_ln1116_7_fu_649_p1, "zext_ln1116_7_fu_649_p1");
    sc_trace(mVcdFile, zext_ln1265_6_fu_794_p1, "zext_ln1265_6_fu_794_p1");
    sc_trace(mVcdFile, zext_ln106_fu_782_p1, "zext_ln106_fu_782_p1");
    sc_trace(mVcdFile, zext_ln1495_fu_806_p1, "zext_ln1495_fu_806_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, add_ln703_fu_815_p2, "add_ln703_fu_815_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, tmp_16_fu_822_p3, "tmp_16_fu_822_p3");
    sc_trace(mVcdFile, tmp_s_fu_298_p3, "tmp_s_fu_298_p3");
    sc_trace(mVcdFile, tmp_3_fu_310_p3, "tmp_3_fu_310_p3");
    sc_trace(mVcdFile, zext_ln1265_1_fu_318_p1, "zext_ln1265_1_fu_318_p1");
    sc_trace(mVcdFile, zext_ln1265_fu_306_p1, "zext_ln1265_fu_306_p1");
    sc_trace(mVcdFile, zext_ln1265_4_fu_340_p1, "zext_ln1265_4_fu_340_p1");
    sc_trace(mVcdFile, zext_ln79_fu_349_p1, "zext_ln79_fu_349_p1");
    sc_trace(mVcdFile, add_ln89_fu_365_p2, "add_ln89_fu_365_p2");
    sc_trace(mVcdFile, tmp_6_fu_371_p3, "tmp_6_fu_371_p3");
    sc_trace(mVcdFile, tmp_9_fu_383_p3, "tmp_9_fu_383_p3");
    sc_trace(mVcdFile, zext_ln1116_fu_379_p1, "zext_ln1116_fu_379_p1");
    sc_trace(mVcdFile, zext_ln1116_5_fu_391_p1, "zext_ln1116_5_fu_391_p1");
    sc_trace(mVcdFile, sub_ln1116_fu_395_p2, "sub_ln1116_fu_395_p2");
    sc_trace(mVcdFile, zext_ln81_fu_409_p1, "zext_ln81_fu_409_p1");
    sc_trace(mVcdFile, add_ln89_1_fu_425_p2, "add_ln89_1_fu_425_p2");
    sc_trace(mVcdFile, zext_ln1116_6_fu_431_p1, "zext_ln1116_6_fu_431_p1");
    sc_trace(mVcdFile, add_ln1116_fu_435_p2, "add_ln1116_fu_435_p2");
    sc_trace(mVcdFile, trunc_ln1116_fu_440_p1, "trunc_ln1116_fu_440_p1");
    sc_trace(mVcdFile, tmp_13_fu_452_p3, "tmp_13_fu_452_p3");
    sc_trace(mVcdFile, p_shl4_cast_fu_444_p3, "p_shl4_cast_fu_444_p3");
    sc_trace(mVcdFile, sext_ln1116_1_fu_460_p1, "sext_ln1116_1_fu_460_p1");
    sc_trace(mVcdFile, trunc_ln89_fu_486_p1, "trunc_ln89_fu_486_p1");
    sc_trace(mVcdFile, add_ln89_2_fu_510_p2, "add_ln89_2_fu_510_p2");
    sc_trace(mVcdFile, tmp_10_fu_515_p3, "tmp_10_fu_515_p3");
    sc_trace(mVcdFile, tmp_11_fu_527_p3, "tmp_11_fu_527_p3");
    sc_trace(mVcdFile, zext_ln1117_fu_523_p1, "zext_ln1117_fu_523_p1");
    sc_trace(mVcdFile, zext_ln1117_8_fu_535_p1, "zext_ln1117_8_fu_535_p1");
    sc_trace(mVcdFile, sub_ln1117_fu_539_p2, "sub_ln1117_fu_539_p2");
    sc_trace(mVcdFile, tmp_17_fu_549_p3, "tmp_17_fu_549_p3");
    sc_trace(mVcdFile, zext_ln1117_10_fu_577_p1, "zext_ln1117_10_fu_577_p1");
    sc_trace(mVcdFile, add_ln1117_fu_581_p2, "add_ln1117_fu_581_p2");
    sc_trace(mVcdFile, tmp_18_fu_590_p3, "tmp_18_fu_590_p3");
    sc_trace(mVcdFile, sext_ln1117_2_fu_586_p1, "sext_ln1117_2_fu_586_p1");
    sc_trace(mVcdFile, sext_ln1117_3_fu_598_p1, "sext_ln1117_3_fu_598_p1");
    sc_trace(mVcdFile, add_ln1117_5_fu_602_p2, "add_ln1117_5_fu_602_p2");
    sc_trace(mVcdFile, add_ln1117_6_fu_608_p2, "add_ln1117_6_fu_608_p2");
    sc_trace(mVcdFile, trunc_ln1117_2_fu_617_p1, "trunc_ln1117_2_fu_617_p1");
    sc_trace(mVcdFile, trunc_ln1117_fu_613_p1, "trunc_ln1117_fu_613_p1");
    sc_trace(mVcdFile, p_shl8_cast_fu_621_p3, "p_shl8_cast_fu_621_p3");
    sc_trace(mVcdFile, add_ln1117_7_fu_629_p2, "add_ln1117_7_fu_629_p2");
    sc_trace(mVcdFile, zext_ln1117_9_fu_573_p1, "zext_ln1117_9_fu_573_p1");
    sc_trace(mVcdFile, grp_fu_830_p3, "grp_fu_830_p3");
    sc_trace(mVcdFile, tmp_4_fu_690_p3, "tmp_4_fu_690_p3");
    sc_trace(mVcdFile, tmp_5_fu_702_p3, "tmp_5_fu_702_p3");
    sc_trace(mVcdFile, zext_ln1265_3_fu_710_p1, "zext_ln1265_3_fu_710_p1");
    sc_trace(mVcdFile, zext_ln1265_2_fu_698_p1, "zext_ln1265_2_fu_698_p1");
    sc_trace(mVcdFile, zext_ln1265_5_fu_732_p1, "zext_ln1265_5_fu_732_p1");
    sc_trace(mVcdFile, trunc_ln106_fu_753_p1, "trunc_ln106_fu_753_p1");
    sc_trace(mVcdFile, add_ln106_fu_777_p2, "add_ln106_fu_777_p2");
    sc_trace(mVcdFile, tmp_14_fu_787_p3, "tmp_14_fu_787_p3");
    sc_trace(mVcdFile, tmp_15_fu_799_p3, "tmp_15_fu_799_p3");
    sc_trace(mVcdFile, sext_ln1265_fu_811_p1, "sext_ln1265_fu_811_p1");
    sc_trace(mVcdFile, grp_fu_830_p2, "grp_fu_830_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

conv2::~conv2() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete K2_W_V_U;
    delete K2_B_V_U;
    delete lenet_mac_muladd_dEe_U11;
}

void conv2::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        c_0_reg_231 = c_reg_935.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln85_fu_498_p2.read()))) {
        c_0_reg_231 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln75_fu_286_p2.read(), ap_const_lv1_1))) {
        i1_0_reg_242 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
                esl_seteq<1,1,1>(icmp_ln100_fu_720_p2.read(), ap_const_lv1_1))) {
        i1_0_reg_242 = i_5_reg_968.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln77_fu_328_p2.read(), ap_const_lv1_1))) {
        i_0_reg_163 = i_reg_842.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_163 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_678_p2.read()))) {
        j2_0_reg_253 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && 
                esl_seteq<1,1,1>(icmp_ln102_fu_741_p2.read(), ap_const_lv1_1))) {
        j2_0_reg_253 = j_1_reg_981.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln79_fu_353_p2.read(), ap_const_lv1_1))) {
        j_0_reg_175 = j_reg_855.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln75_fu_286_p2.read(), ap_const_lv1_0))) {
        j_0_reg_175 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_741_p2.read()))) {
        k4_0_reg_275 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        k4_0_reg_275 = k_reg_1008.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln83_fu_474_p2.read()))) {
        k_0_reg_220 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(icmp_ln87_fu_561_p2.read(), ap_const_lv1_1))) {
        k_0_reg_220 = k_1_reg_917.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
         esl_seteq<1,1,1>(icmp_ln104_fu_765_p2.read(), ap_const_lv1_1))) {
        set3_0_reg_264 = set_reg_995.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_720_p2.read()))) {
        set3_0_reg_264 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(icmp_ln85_fu_498_p2.read(), ap_const_lv1_1))) {
        set_0_reg_209 = set_1_reg_904.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln81_fu_413_p2.read()))) {
        set_0_reg_209 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln81_fu_413_p2.read(), ap_const_lv1_1))) {
        x_0_reg_187 = x_reg_868.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln77_fu_328_p2.read()))) {
        x_0_reg_187 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln79_fu_353_p2.read()))) {
        y_0_reg_198 = ap_const_lv3_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(icmp_ln83_fu_474_p2.read(), ap_const_lv1_1))) {
        y_0_reg_198 = y_reg_886.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln87_fu_561_p2.read()))) {
        add_ln1116_3_reg_945 = add_ln1116_3_fu_640_p2.read();
        add_ln1117_8_reg_940 = add_ln1117_8_fu_635_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_678_p2.read()))) {
        add_ln1265_1_reg_973 = add_ln1265_1_fu_714_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln77_fu_328_p2.read()))) {
        add_ln1265_2_reg_860 = add_ln1265_2_fu_344_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_720_p2.read()))) {
        add_ln1265_3_reg_986 = add_ln1265_3_fu_736_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln75_fu_286_p2.read(), ap_const_lv1_0))) {
        add_ln1265_reg_847 = add_ln1265_fu_322_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        c_reg_935 = c_fu_567_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        i_5_reg_968 = i_5_fu_684_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_842 = i_fu_292_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        j_1_reg_981 = j_1_fu_726_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        j_reg_855 = j_fu_334_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        k_1_reg_917 = k_1_fu_504_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        k_reg_1008 = k_fu_771_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln104_fu_765_p2.read()))) {
        out_V_addr_3_reg_1023 =  (sc_lv<11>) (zext_ln1495_fu_806_p1.read());
        out_V_addr_reg_1013 =  (sc_lv<11>) (zext_ln1265_6_fu_794_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln85_fu_498_p2.read()))) {
        out_V_addr_4_reg_927 =  (sc_lv<11>) (zext_ln1265_7_fu_556_p1.read());
        sext_ln1117_reg_922 = sext_ln1117_fu_545_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        set_1_reg_904 = set_1_fu_480_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        set_reg_995 = set_fu_747_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln79_fu_353_p2.read()))) {
        sext_ln1116_reg_873 = sext_ln1116_fu_401_p1.read();
        zext_ln89_reg_878 = zext_ln89_fu_405_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln83_fu_474_p2.read()))) {
        shl_ln3_reg_909 = shl_ln3_fu_490_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln102_fu_741_p2.read()))) {
        shl_ln_reg_1000 = shl_ln_fu_757_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln81_fu_413_p2.read()))) {
        sub_ln1116_1_reg_891 = sub_ln1116_1_fu_464_p2.read();
        zext_ln83_reg_896 = zext_ln83_fu_470_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        trunc_ln_reg_960 = grp_fu_830_p3.read().range(25, 10);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        x_reg_868 = x_fu_359_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        y_reg_886 = y_fu_419_p2.read();
    }
}

void conv2::thread_K2_B_V_address0() {
    K2_B_V_address0 =  (sc_lv<4>) (zext_ln106_fu_782_p1.read());
}

void conv2::thread_K2_B_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        K2_B_V_ce0 = ap_const_logic_1;
    } else {
        K2_B_V_ce0 = ap_const_logic_0;
    }
}

void conv2::thread_K2_W_V_address0() {
    K2_W_V_address0 =  (sc_lv<12>) (zext_ln1117_11_fu_645_p1.read());
}

void conv2::thread_K2_W_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        K2_W_V_ce0 = ap_const_logic_1;
    } else {
        K2_W_V_ce0 = ap_const_logic_0;
    }
}

void conv2::thread_P1_out_V_address0() {
    P1_out_V_address0 =  (sc_lv<11>) (zext_ln1116_7_fu_649_p1.read());
}

void conv2::thread_P1_out_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        P1_out_V_ce0 = ap_const_logic_1;
    } else {
        P1_out_V_ce0 = ap_const_logic_0;
    }
}

void conv2::thread_add_ln106_fu_777_p2() {
    add_ln106_fu_777_p2 = (!shl_ln_reg_1000.read().is_01() || !k4_0_reg_275.read().is_01())? sc_lv<4>(): (sc_biguint<4>(shl_ln_reg_1000.read()) + sc_biguint<4>(k4_0_reg_275.read()));
}

void conv2::thread_add_ln1116_3_fu_640_p2() {
    add_ln1116_3_fu_640_p2 = (!sub_ln1116_1_reg_891.read().is_01() || !zext_ln1117_9_fu_573_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(sub_ln1116_1_reg_891.read()) + sc_biguint<12>(zext_ln1117_9_fu_573_p1.read()));
}

void conv2::thread_add_ln1116_fu_435_p2() {
    add_ln1116_fu_435_p2 = (!sext_ln1116_reg_873.read().is_01() || !zext_ln1116_6_fu_431_p1.read().is_01())? sc_lv<10>(): (sc_bigint<10>(sext_ln1116_reg_873.read()) + sc_biguint<10>(zext_ln1116_6_fu_431_p1.read()));
}

void conv2::thread_add_ln1117_5_fu_602_p2() {
    add_ln1117_5_fu_602_p2 = (!sext_ln1117_2_fu_586_p1.read().is_01() || !sext_ln1117_3_fu_598_p1.read().is_01())? sc_lv<64>(): (sc_bigint<64>(sext_ln1117_2_fu_586_p1.read()) + sc_bigint<64>(sext_ln1117_3_fu_598_p1.read()));
}

void conv2::thread_add_ln1117_6_fu_608_p2() {
    add_ln1117_6_fu_608_p2 = (!add_ln1117_5_fu_602_p2.read().is_01() || !zext_ln89_reg_878.read().is_01())? sc_lv<64>(): (sc_biguint<64>(add_ln1117_5_fu_602_p2.read()) + sc_biguint<64>(zext_ln89_reg_878.read()));
}

void conv2::thread_add_ln1117_7_fu_629_p2() {
    add_ln1117_7_fu_629_p2 = (!trunc_ln1117_fu_613_p1.read().is_01() || !p_shl8_cast_fu_621_p3.read().is_01())? sc_lv<13>(): (sc_biguint<13>(trunc_ln1117_fu_613_p1.read()) + sc_biguint<13>(p_shl8_cast_fu_621_p3.read()));
}

void conv2::thread_add_ln1117_8_fu_635_p2() {
    add_ln1117_8_fu_635_p2 = (!add_ln1117_7_fu_629_p2.read().is_01() || !zext_ln83_reg_896.read().is_01())? sc_lv<13>(): (sc_biguint<13>(add_ln1117_7_fu_629_p2.read()) + sc_biguint<13>(zext_ln83_reg_896.read()));
}

void conv2::thread_add_ln1117_fu_581_p2() {
    add_ln1117_fu_581_p2 = (!sext_ln1117_reg_922.read().is_01() || !zext_ln1117_10_fu_577_p1.read().is_01())? sc_lv<9>(): (sc_bigint<9>(sext_ln1117_reg_922.read()) + sc_biguint<9>(zext_ln1117_10_fu_577_p1.read()));
}

void conv2::thread_add_ln1265_1_fu_714_p2() {
    add_ln1265_1_fu_714_p2 = (!zext_ln1265_3_fu_710_p1.read().is_01() || !zext_ln1265_2_fu_698_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln1265_3_fu_710_p1.read()) + sc_biguint<8>(zext_ln1265_2_fu_698_p1.read()));
}

void conv2::thread_add_ln1265_2_fu_344_p2() {
    add_ln1265_2_fu_344_p2 = (!zext_ln1265_4_fu_340_p1.read().is_01() || !add_ln1265_reg_847.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln1265_4_fu_340_p1.read()) + sc_biguint<8>(add_ln1265_reg_847.read()));
}

void conv2::thread_add_ln1265_3_fu_736_p2() {
    add_ln1265_3_fu_736_p2 = (!zext_ln1265_5_fu_732_p1.read().is_01() || !add_ln1265_1_reg_973.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln1265_5_fu_732_p1.read()) + sc_biguint<8>(add_ln1265_1_reg_973.read()));
}

void conv2::thread_add_ln1265_fu_322_p2() {
    add_ln1265_fu_322_p2 = (!zext_ln1265_1_fu_318_p1.read().is_01() || !zext_ln1265_fu_306_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln1265_1_fu_318_p1.read()) + sc_biguint<8>(zext_ln1265_fu_306_p1.read()));
}

void conv2::thread_add_ln703_fu_815_p2() {
    add_ln703_fu_815_p2 = (!out_V_q0.read().is_01() || !sext_ln1265_fu_811_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(out_V_q0.read()) + sc_bigint<16>(sext_ln1265_fu_811_p1.read()));
}

void conv2::thread_add_ln89_1_fu_425_p2() {
    add_ln89_1_fu_425_p2 = (!zext_ln81_fu_409_p1.read().is_01() || !j_0_reg_175.read().is_01())? sc_lv<4>(): (sc_biguint<4>(zext_ln81_fu_409_p1.read()) + sc_biguint<4>(j_0_reg_175.read()));
}

void conv2::thread_add_ln89_2_fu_510_p2() {
    add_ln89_2_fu_510_p2 = (!k_0_reg_220.read().is_01() || !shl_ln3_reg_909.read().is_01())? sc_lv<4>(): (sc_biguint<4>(k_0_reg_220.read()) + sc_biguint<4>(shl_ln3_reg_909.read()));
}

void conv2::thread_add_ln89_fu_365_p2() {
    add_ln89_fu_365_p2 = (!zext_ln79_fu_349_p1.read().is_01() || !i_0_reg_163.read().is_01())? sc_lv<4>(): (sc_biguint<4>(zext_ln79_fu_349_p1.read()) + sc_biguint<4>(i_0_reg_163.read()));
}

void conv2::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void conv2::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void conv2::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void conv2::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void conv2::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void conv2::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void conv2::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void conv2::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void conv2::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void conv2::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void conv2::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void conv2::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void conv2::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void conv2::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void conv2::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void conv2::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void conv2::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void conv2::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void conv2::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
          esl_seteq<1,1,1>(icmp_ln98_fu_678_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void conv2::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void conv2::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
         esl_seteq<1,1,1>(icmp_ln98_fu_678_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void conv2::thread_c_fu_567_p2() {
    c_fu_567_p2 = (!c_0_reg_231.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(c_0_reg_231.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void conv2::thread_grp_fu_830_p2() {
    grp_fu_830_p2 = esl_concat<16,10>(out_V_q0.read(), ap_const_lv10_0);
}

void conv2::thread_i_5_fu_684_p2() {
    i_5_fu_684_p2 = (!i1_0_reg_242.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i1_0_reg_242.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void conv2::thread_i_fu_292_p2() {
    i_fu_292_p2 = (!i_0_reg_163.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_0_reg_163.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void conv2::thread_icmp_ln100_fu_720_p2() {
    icmp_ln100_fu_720_p2 = (!j2_0_reg_253.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(j2_0_reg_253.read() == ap_const_lv4_A);
}

void conv2::thread_icmp_ln102_fu_741_p2() {
    icmp_ln102_fu_741_p2 = (!set3_0_reg_264.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(set3_0_reg_264.read() == ap_const_lv2_2);
}

void conv2::thread_icmp_ln104_fu_765_p2() {
    icmp_ln104_fu_765_p2 = (!k4_0_reg_275.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(k4_0_reg_275.read() == ap_const_lv4_8);
}

void conv2::thread_icmp_ln75_fu_286_p2() {
    icmp_ln75_fu_286_p2 = (!i_0_reg_163.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_163.read() == ap_const_lv4_A);
}

void conv2::thread_icmp_ln77_fu_328_p2() {
    icmp_ln77_fu_328_p2 = (!j_0_reg_175.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(j_0_reg_175.read() == ap_const_lv4_A);
}

void conv2::thread_icmp_ln79_fu_353_p2() {
    icmp_ln79_fu_353_p2 = (!x_0_reg_187.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(x_0_reg_187.read() == ap_const_lv3_5);
}

void conv2::thread_icmp_ln81_fu_413_p2() {
    icmp_ln81_fu_413_p2 = (!y_0_reg_198.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(y_0_reg_198.read() == ap_const_lv3_5);
}

void conv2::thread_icmp_ln83_fu_474_p2() {
    icmp_ln83_fu_474_p2 = (!set_0_reg_209.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(set_0_reg_209.read() == ap_const_lv2_2);
}

void conv2::thread_icmp_ln85_fu_498_p2() {
    icmp_ln85_fu_498_p2 = (!k_0_reg_220.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(k_0_reg_220.read() == ap_const_lv4_8);
}

void conv2::thread_icmp_ln87_fu_561_p2() {
    icmp_ln87_fu_561_p2 = (!c_0_reg_231.read().is_01() || !ap_const_lv3_6.is_01())? sc_lv<1>(): sc_lv<1>(c_0_reg_231.read() == ap_const_lv3_6);
}

void conv2::thread_icmp_ln98_fu_678_p2() {
    icmp_ln98_fu_678_p2 = (!i1_0_reg_242.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(i1_0_reg_242.read() == ap_const_lv4_A);
}

void conv2::thread_j_1_fu_726_p2() {
    j_1_fu_726_p2 = (!j2_0_reg_253.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(j2_0_reg_253.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void conv2::thread_j_fu_334_p2() {
    j_fu_334_p2 = (!j_0_reg_175.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(j_0_reg_175.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void conv2::thread_k_1_fu_504_p2() {
    k_1_fu_504_p2 = (!k_0_reg_220.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(k_0_reg_220.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void conv2::thread_k_fu_771_p2() {
    k_fu_771_p2 = (!k4_0_reg_275.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(k4_0_reg_275.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void conv2::thread_out_V_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()))) {
        out_V_address0 = out_V_addr_3_reg_1023.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        out_V_address0 = out_V_addr_reg_1013.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        out_V_address0 =  (sc_lv<11>) (zext_ln1265_6_fu_794_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()))) {
        out_V_address0 = out_V_addr_4_reg_927.read();
    } else {
        out_V_address0 = "XXXXXXXXXXX";
    }
}

void conv2::thread_out_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()))) {
        out_V_ce0 = ap_const_logic_1;
    } else {
        out_V_ce0 = ap_const_logic_0;
    }
}

void conv2::thread_out_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        out_V_d0 = ap_const_lv16_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        out_V_d0 = add_ln703_fu_815_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        out_V_d0 = trunc_ln_reg_960.read();
    } else {
        out_V_d0 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void conv2::thread_out_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_16_fu_822_p3.read())))) {
        out_V_we0 = ap_const_logic_1;
    } else {
        out_V_we0 = ap_const_logic_0;
    }
}

void conv2::thread_p_shl4_cast_fu_444_p3() {
    p_shl4_cast_fu_444_p3 = esl_concat<9,3>(trunc_ln1116_fu_440_p1.read(), ap_const_lv3_0);
}

void conv2::thread_p_shl8_cast_fu_621_p3() {
    p_shl8_cast_fu_621_p3 = esl_concat<11,2>(trunc_ln1117_2_fu_617_p1.read(), ap_const_lv2_0);
}

void conv2::thread_set_1_fu_480_p2() {
    set_1_fu_480_p2 = (!set_0_reg_209.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(set_0_reg_209.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv2::thread_set_fu_747_p2() {
    set_fu_747_p2 = (!set3_0_reg_264.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(set3_0_reg_264.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv2::thread_sext_ln1116_1_fu_460_p1() {
    sext_ln1116_1_fu_460_p1 = esl_sext<12,11>(tmp_13_fu_452_p3.read());
}

void conv2::thread_sext_ln1116_fu_401_p1() {
    sext_ln1116_fu_401_p1 = esl_sext<10,9>(sub_ln1116_fu_395_p2.read());
}

void conv2::thread_sext_ln1117_2_fu_586_p1() {
    sext_ln1117_2_fu_586_p1 = esl_sext<64,9>(add_ln1117_fu_581_p2.read());
}

void conv2::thread_sext_ln1117_3_fu_598_p1() {
    sext_ln1117_3_fu_598_p1 = esl_sext<64,11>(tmp_18_fu_590_p3.read());
}

void conv2::thread_sext_ln1117_fu_545_p1() {
    sext_ln1117_fu_545_p1 = esl_sext<9,8>(sub_ln1117_fu_539_p2.read());
}

void conv2::thread_sext_ln1265_fu_811_p1() {
    sext_ln1265_fu_811_p1 = esl_sext<16,8>(K2_B_V_q0.read());
}

void conv2::thread_shl_ln3_fu_490_p3() {
    shl_ln3_fu_490_p3 = esl_concat<1,3>(trunc_ln89_fu_486_p1.read(), ap_const_lv3_0);
}

void conv2::thread_shl_ln_fu_757_p3() {
    shl_ln_fu_757_p3 = esl_concat<1,3>(trunc_ln106_fu_753_p1.read(), ap_const_lv3_0);
}

void conv2::thread_sub_ln1116_1_fu_464_p2() {
    sub_ln1116_1_fu_464_p2 = (!p_shl4_cast_fu_444_p3.read().is_01() || !sext_ln1116_1_fu_460_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(p_shl4_cast_fu_444_p3.read()) - sc_bigint<12>(sext_ln1116_1_fu_460_p1.read()));
}

void conv2::thread_sub_ln1116_fu_395_p2() {
    sub_ln1116_fu_395_p2 = (!zext_ln1116_fu_379_p1.read().is_01() || !zext_ln1116_5_fu_391_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(zext_ln1116_fu_379_p1.read()) - sc_biguint<9>(zext_ln1116_5_fu_391_p1.read()));
}

void conv2::thread_sub_ln1117_fu_539_p2() {
    sub_ln1117_fu_539_p2 = (!zext_ln1117_fu_523_p1.read().is_01() || !zext_ln1117_8_fu_535_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln1117_fu_523_p1.read()) - sc_biguint<8>(zext_ln1117_8_fu_535_p1.read()));
}

void conv2::thread_tmp_10_fu_515_p3() {
    tmp_10_fu_515_p3 = esl_concat<4,3>(add_ln89_2_fu_510_p2.read(), ap_const_lv3_0);
}

void conv2::thread_tmp_11_fu_527_p3() {
    tmp_11_fu_527_p3 = esl_concat<4,1>(add_ln89_2_fu_510_p2.read(), ap_const_lv1_0);
}

void conv2::thread_tmp_13_fu_452_p3() {
    tmp_13_fu_452_p3 = esl_concat<10,1>(add_ln1116_fu_435_p2.read(), ap_const_lv1_0);
}

void conv2::thread_tmp_14_fu_787_p3() {
    tmp_14_fu_787_p3 = esl_concat<8,4>(add_ln1265_3_reg_986.read(), add_ln106_fu_777_p2.read());
}

void conv2::thread_tmp_15_fu_799_p3() {
    tmp_15_fu_799_p3 = esl_concat<8,4>(add_ln1265_3_reg_986.read(), k4_0_reg_275.read());
}

void conv2::thread_tmp_16_fu_822_p3() {
    tmp_16_fu_822_p3 = out_V_q0.read().range(15, 15);
}

void conv2::thread_tmp_17_fu_549_p3() {
    tmp_17_fu_549_p3 = esl_concat<8,4>(add_ln1265_2_reg_860.read(), add_ln89_2_fu_510_p2.read());
}

void conv2::thread_tmp_18_fu_590_p3() {
    tmp_18_fu_590_p3 = esl_concat<9,2>(add_ln1117_fu_581_p2.read(), ap_const_lv2_0);
}

void conv2::thread_tmp_3_fu_310_p3() {
    tmp_3_fu_310_p3 = esl_concat<4,1>(i_0_reg_163.read(), ap_const_lv1_0);
}

void conv2::thread_tmp_4_fu_690_p3() {
    tmp_4_fu_690_p3 = esl_concat<4,3>(i1_0_reg_242.read(), ap_const_lv3_0);
}

void conv2::thread_tmp_5_fu_702_p3() {
    tmp_5_fu_702_p3 = esl_concat<4,1>(i1_0_reg_242.read(), ap_const_lv1_0);
}

void conv2::thread_tmp_6_fu_371_p3() {
    tmp_6_fu_371_p3 = esl_concat<4,4>(add_ln89_fu_365_p2.read(), ap_const_lv4_0);
}

void conv2::thread_tmp_9_fu_383_p3() {
    tmp_9_fu_383_p3 = esl_concat<4,1>(add_ln89_fu_365_p2.read(), ap_const_lv1_0);
}

void conv2::thread_tmp_s_fu_298_p3() {
    tmp_s_fu_298_p3 = esl_concat<4,3>(i_0_reg_163.read(), ap_const_lv3_0);
}

void conv2::thread_trunc_ln106_fu_753_p1() {
    trunc_ln106_fu_753_p1 = set3_0_reg_264.read().range(1-1, 0);
}

void conv2::thread_trunc_ln1116_fu_440_p1() {
    trunc_ln1116_fu_440_p1 = add_ln1116_fu_435_p2.read().range(9-1, 0);
}

void conv2::thread_trunc_ln1117_2_fu_617_p1() {
    trunc_ln1117_2_fu_617_p1 = add_ln1117_6_fu_608_p2.read().range(11-1, 0);
}

void conv2::thread_trunc_ln1117_fu_613_p1() {
    trunc_ln1117_fu_613_p1 = add_ln1117_6_fu_608_p2.read().range(13-1, 0);
}

void conv2::thread_trunc_ln89_fu_486_p1() {
    trunc_ln89_fu_486_p1 = set_0_reg_209.read().range(1-1, 0);
}

void conv2::thread_x_fu_359_p2() {
    x_fu_359_p2 = (!x_0_reg_187.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(x_0_reg_187.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void conv2::thread_y_fu_419_p2() {
    y_fu_419_p2 = (!y_0_reg_198.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(y_0_reg_198.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void conv2::thread_zext_ln106_fu_782_p1() {
    zext_ln106_fu_782_p1 = esl_zext<64,4>(add_ln106_fu_777_p2.read());
}

void conv2::thread_zext_ln1116_5_fu_391_p1() {
    zext_ln1116_5_fu_391_p1 = esl_zext<9,5>(tmp_9_fu_383_p3.read());
}

void conv2::thread_zext_ln1116_6_fu_431_p1() {
    zext_ln1116_6_fu_431_p1 = esl_zext<10,4>(add_ln89_1_fu_425_p2.read());
}

void conv2::thread_zext_ln1116_7_fu_649_p1() {
    zext_ln1116_7_fu_649_p1 = esl_zext<64,12>(add_ln1116_3_reg_945.read());
}

void conv2::thread_zext_ln1116_fu_379_p1() {
    zext_ln1116_fu_379_p1 = esl_zext<9,8>(tmp_6_fu_371_p3.read());
}

void conv2::thread_zext_ln1117_10_fu_577_p1() {
    zext_ln1117_10_fu_577_p1 = esl_zext<9,3>(c_0_reg_231.read());
}

void conv2::thread_zext_ln1117_11_fu_645_p1() {
    zext_ln1117_11_fu_645_p1 = esl_zext<64,13>(add_ln1117_8_reg_940.read());
}

void conv2::thread_zext_ln1117_8_fu_535_p1() {
    zext_ln1117_8_fu_535_p1 = esl_zext<8,5>(tmp_11_fu_527_p3.read());
}

void conv2::thread_zext_ln1117_9_fu_573_p1() {
    zext_ln1117_9_fu_573_p1 = esl_zext<12,3>(c_0_reg_231.read());
}

void conv2::thread_zext_ln1117_fu_523_p1() {
    zext_ln1117_fu_523_p1 = esl_zext<8,7>(tmp_10_fu_515_p3.read());
}

void conv2::thread_zext_ln1265_1_fu_318_p1() {
    zext_ln1265_1_fu_318_p1 = esl_zext<8,5>(tmp_3_fu_310_p3.read());
}

void conv2::thread_zext_ln1265_2_fu_698_p1() {
    zext_ln1265_2_fu_698_p1 = esl_zext<8,7>(tmp_4_fu_690_p3.read());
}

void conv2::thread_zext_ln1265_3_fu_710_p1() {
    zext_ln1265_3_fu_710_p1 = esl_zext<8,5>(tmp_5_fu_702_p3.read());
}

void conv2::thread_zext_ln1265_4_fu_340_p1() {
    zext_ln1265_4_fu_340_p1 = esl_zext<8,4>(j_0_reg_175.read());
}

void conv2::thread_zext_ln1265_5_fu_732_p1() {
    zext_ln1265_5_fu_732_p1 = esl_zext<8,4>(j2_0_reg_253.read());
}

void conv2::thread_zext_ln1265_6_fu_794_p1() {
    zext_ln1265_6_fu_794_p1 = esl_zext<64,12>(tmp_14_fu_787_p3.read());
}

void conv2::thread_zext_ln1265_7_fu_556_p1() {
    zext_ln1265_7_fu_556_p1 = esl_zext<64,12>(tmp_17_fu_549_p3.read());
}

void conv2::thread_zext_ln1265_fu_306_p1() {
    zext_ln1265_fu_306_p1 = esl_zext<8,7>(tmp_s_fu_298_p3.read());
}

void conv2::thread_zext_ln1495_fu_806_p1() {
    zext_ln1495_fu_806_p1 = esl_zext<64,12>(tmp_15_fu_799_p3.read());
}

void conv2::thread_zext_ln79_fu_349_p1() {
    zext_ln79_fu_349_p1 = esl_zext<4,3>(x_0_reg_187.read());
}

void conv2::thread_zext_ln81_fu_409_p1() {
    zext_ln81_fu_409_p1 = esl_zext<4,3>(y_0_reg_198.read());
}

void conv2::thread_zext_ln83_fu_470_p1() {
    zext_ln83_fu_470_p1 = esl_zext<13,3>(y_0_reg_198.read());
}

void conv2::thread_zext_ln89_fu_405_p1() {
    zext_ln89_fu_405_p1 = esl_zext<64,3>(x_0_reg_187.read());
}

void conv2::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln75_fu_286_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state12;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln77_fu_328_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln79_fu_353_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(icmp_ln81_fu_413_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(icmp_ln83_fu_474_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(icmp_ln85_fu_498_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(icmp_ln87_fu_561_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 2048 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(icmp_ln98_fu_678_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state13;
            }
            break;
        case 4096 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && esl_seteq<1,1,1>(icmp_ln100_fu_720_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state12;
            } else {
                ap_NS_fsm = ap_ST_fsm_state14;
            }
            break;
        case 8192 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && esl_seteq<1,1,1>(icmp_ln102_fu_741_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_state15;
            }
            break;
        case 16384 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && esl_seteq<1,1,1>(icmp_ln104_fu_765_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state14;
            } else {
                ap_NS_fsm = ap_ST_fsm_state16;
            }
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<18>) ("XXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

