// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "conv3.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic conv3::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic conv3::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<14> conv3::ap_ST_fsm_state1 = "1";
const sc_lv<14> conv3::ap_ST_fsm_state2 = "10";
const sc_lv<14> conv3::ap_ST_fsm_state3 = "100";
const sc_lv<14> conv3::ap_ST_fsm_state4 = "1000";
const sc_lv<14> conv3::ap_ST_fsm_state5 = "10000";
const sc_lv<14> conv3::ap_ST_fsm_state6 = "100000";
const sc_lv<14> conv3::ap_ST_fsm_state7 = "1000000";
const sc_lv<14> conv3::ap_ST_fsm_state8 = "10000000";
const sc_lv<14> conv3::ap_ST_fsm_state9 = "100000000";
const sc_lv<14> conv3::ap_ST_fsm_state10 = "1000000000";
const sc_lv<14> conv3::ap_ST_fsm_state11 = "10000000000";
const sc_lv<14> conv3::ap_ST_fsm_state12 = "100000000000";
const sc_lv<14> conv3::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<14> conv3::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<32> conv3::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> conv3::ap_const_lv32_1 = "1";
const sc_lv<1> conv3::ap_const_lv1_0 = "0";
const sc_lv<32> conv3::ap_const_lv32_2 = "10";
const sc_lv<32> conv3::ap_const_lv32_3 = "11";
const sc_lv<32> conv3::ap_const_lv32_4 = "100";
const sc_lv<32> conv3::ap_const_lv32_5 = "101";
const sc_lv<32> conv3::ap_const_lv32_6 = "110";
const sc_lv<32> conv3::ap_const_lv32_7 = "111";
const sc_lv<32> conv3::ap_const_lv32_9 = "1001";
const sc_lv<32> conv3::ap_const_lv32_A = "1010";
const sc_lv<32> conv3::ap_const_lv32_C = "1100";
const sc_lv<3> conv3::ap_const_lv3_0 = "000";
const sc_lv<1> conv3::ap_const_lv1_1 = "1";
const sc_lv<4> conv3::ap_const_lv4_0 = "0000";
const sc_lv<5> conv3::ap_const_lv5_0 = "00000";
const sc_lv<32> conv3::ap_const_lv32_8 = "1000";
const sc_lv<32> conv3::ap_const_lv32_D = "1101";
const sc_lv<32> conv3::ap_const_lv32_B = "1011";
const sc_lv<16> conv3::ap_const_lv16_0 = "0000000000000000";
const sc_lv<3> conv3::ap_const_lv3_5 = "101";
const sc_lv<3> conv3::ap_const_lv3_1 = "1";
const sc_lv<2> conv3::ap_const_lv2_0 = "00";
const sc_lv<4> conv3::ap_const_lv4_F = "1111";
const sc_lv<4> conv3::ap_const_lv4_1 = "1";
const sc_lv<4> conv3::ap_const_lv4_8 = "1000";
const sc_lv<5> conv3::ap_const_lv5_10 = "10000";
const sc_lv<5> conv3::ap_const_lv5_1 = "1";
const sc_lv<10> conv3::ap_const_lv10_0 = "0000000000";
const sc_lv<32> conv3::ap_const_lv32_19 = "11001";
const sc_lv<32> conv3::ap_const_lv32_F = "1111";
const bool conv3::ap_const_boolean_1 = true;

conv3::conv3(sc_module_name name) : sc_module(name), mVcdFile(0) {
    K3_W_V_U = new conv3_K3_W_V("K3_W_V_U");
    K3_W_V_U->clk(ap_clk);
    K3_W_V_U->reset(ap_rst);
    K3_W_V_U->address0(K3_W_V_address0);
    K3_W_V_U->ce0(K3_W_V_ce0);
    K3_W_V_U->q0(K3_W_V_q0);
    K3_B_V_U = new conv3_K3_B_V("K3_B_V_U");
    K3_B_V_U->clk(ap_clk);
    K3_B_V_U->reset(ap_rst);
    K3_B_V_U->address0(K3_B_V_address0);
    K3_B_V_U->ce0(K3_B_V_ce0);
    K3_B_V_U->q0(K3_B_V_q0);
    lenet_mac_muladd_eOg_U19 = new lenet_mac_muladd_eOg<1,1,8,16,26,26>("lenet_mac_muladd_eOg_U19");
    lenet_mac_muladd_eOg_U19->din0(K3_W_V_q0);
    lenet_mac_muladd_eOg_U19->din1(P2_out_V_q0);
    lenet_mac_muladd_eOg_U19->din2(grp_fu_547_p2);
    lenet_mac_muladd_eOg_U19->dout(grp_fu_547_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_K3_B_V_address0);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( zext_ln175_fu_517_p1 );

    SC_METHOD(thread_K3_B_V_ce0);
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_K3_W_V_address0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( zext_ln1117_7_fu_443_p1 );

    SC_METHOD(thread_K3_W_V_ce0);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_P2_out_V_address0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( zext_ln1116_4_fu_447_p1 );

    SC_METHOD(thread_P2_out_V_ce0);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_add_ln1116_1_fu_288_p2);
    sensitive << ( add_ln1116_reg_569 );
    sensitive << ( zext_ln1116_3_fu_284_p1 );

    SC_METHOD(thread_add_ln1116_2_fu_438_p2);
    sensitive << ( tmp_19_cast_reg_587 );
    sensitive << ( zext_ln1117_fu_371_p1 );

    SC_METHOD(thread_add_ln1116_fu_262_p2);
    sensitive << ( zext_ln1116_fu_246_p1 );
    sensitive << ( zext_ln1116_1_fu_258_p1 );

    SC_METHOD(thread_add_ln1117_1_fu_400_p2);
    sensitive << ( zext_ln1117_5_fu_384_p1 );
    sensitive << ( zext_ln1117_6_fu_396_p1 );

    SC_METHOD(thread_add_ln1117_2_fu_406_p2);
    sensitive << ( zext_ln158_reg_564 );
    sensitive << ( add_ln1117_1_fu_400_p2 );

    SC_METHOD(thread_add_ln1117_3_fu_427_p2);
    sensitive << ( trunc_ln1117_fu_411_p1 );
    sensitive << ( p_shl1_cast_fu_419_p3 );

    SC_METHOD(thread_add_ln1117_4_fu_433_p2);
    sensitive << ( zext_ln1116_2_reg_582 );
    sensitive << ( add_ln1117_3_fu_427_p2 );

    SC_METHOD(thread_add_ln1117_fu_379_p2);
    sensitive << ( zext_ln1265_reg_613 );
    sensitive << ( zext_ln1117_4_fu_375_p1 );

    SC_METHOD(thread_add_ln148_fu_236_p2);
    sensitive << ( x_0_0_0_reg_152 );

    SC_METHOD(thread_add_ln150_fu_274_p2);
    sensitive << ( y_0_0_0_reg_163 );

    SC_METHOD(thread_add_ln152_fu_307_p2);
    sensitive << ( set_0_0_0_reg_174 );

    SC_METHOD(thread_add_ln154_fu_331_p2);
    sensitive << ( k_0_0_0_reg_185 );

    SC_METHOD(thread_add_ln156_fu_365_p2);
    sensitive << ( c_0_0_0_reg_196 );

    SC_METHOD(thread_add_ln158_fu_337_p2);
    sensitive << ( shl_ln1_reg_600 );
    sensitive << ( zext_ln154_fu_321_p1 );

    SC_METHOD(thread_add_ln171_fu_482_p2);
    sensitive << ( set3_0_0_0_reg_207 );

    SC_METHOD(thread_add_ln173_fu_506_p2);
    sensitive << ( k4_0_0_0_reg_218 );

    SC_METHOD(thread_add_ln175_fu_512_p2);
    sensitive << ( shl_ln_reg_664 );
    sensitive << ( zext_ln173_fu_496_p1 );

    SC_METHOD(thread_add_ln703_fu_527_p2);
    sensitive << ( out_0_0_V_q0 );
    sensitive << ( sext_ln1265_fu_523_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( icmp_ln171_fu_476_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( icmp_ln171_fu_476_p2 );

    SC_METHOD(thread_grp_fu_547_p2);
    sensitive << ( out_0_0_V_q0 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_icmp_ln148_fu_230_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( x_0_0_0_reg_152 );

    SC_METHOD(thread_icmp_ln150_fu_268_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_0_0_0_reg_163 );

    SC_METHOD(thread_icmp_ln152_fu_301_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( set_0_0_0_reg_174 );

    SC_METHOD(thread_icmp_ln154_fu_325_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( k_0_0_0_reg_185 );

    SC_METHOD(thread_icmp_ln156_fu_359_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( c_0_0_0_reg_196 );

    SC_METHOD(thread_icmp_ln171_fu_476_p2);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( set3_0_0_0_reg_207 );

    SC_METHOD(thread_icmp_ln173_fu_500_p2);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( k4_0_0_0_reg_218 );

    SC_METHOD(thread_out_0_0_V_address0);
    sensitive << ( out_0_0_V_addr_2_reg_618 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( out_0_0_V_addr_reg_677 );
    sensitive << ( out_0_0_V_addr_1_reg_687 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( zext_ln175_fu_517_p1 );
    sensitive << ( zext_ln176_fu_534_p1 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_out_0_0_V_ce0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_out_0_0_V_d0);
    sensitive << ( trunc_ln_reg_651 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( add_ln703_fu_527_p2 );

    SC_METHOD(thread_out_0_0_V_we0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( tmp_11_fu_539_p3 );

    SC_METHOD(thread_p_shl1_cast_fu_419_p3);
    sensitive << ( trunc_ln1117_1_fu_415_p1 );

    SC_METHOD(thread_sext_ln1265_fu_523_p1);
    sensitive << ( K3_B_V_q0 );

    SC_METHOD(thread_shl_ln1_fu_313_p3);
    sensitive << ( set_0_0_0_reg_174 );

    SC_METHOD(thread_shl_ln_fu_488_p3);
    sensitive << ( set3_0_0_0_reg_207 );

    SC_METHOD(thread_tmp_11_fu_539_p3);
    sensitive << ( out_0_0_V_q0 );

    SC_METHOD(thread_tmp_12_fu_388_p3);
    sensitive << ( add_ln1117_fu_379_p2 );

    SC_METHOD(thread_tmp_19_cast_fu_293_p3);
    sensitive << ( add_ln1116_1_fu_288_p2 );

    SC_METHOD(thread_tmp_2_fu_347_p3);
    sensitive << ( add_ln158_fu_337_p2 );

    SC_METHOD(thread_tmp_s_fu_250_p3);
    sensitive << ( x_0_0_0_reg_152 );

    SC_METHOD(thread_trunc_ln1117_1_fu_415_p1);
    sensitive << ( add_ln1117_2_fu_406_p2 );

    SC_METHOD(thread_trunc_ln1117_fu_411_p1);
    sensitive << ( add_ln1117_2_fu_406_p2 );

    SC_METHOD(thread_zext_ln1116_1_fu_258_p1);
    sensitive << ( tmp_s_fu_250_p3 );

    SC_METHOD(thread_zext_ln1116_2_fu_280_p1);
    sensitive << ( y_0_0_0_reg_163 );

    SC_METHOD(thread_zext_ln1116_3_fu_284_p1);
    sensitive << ( y_0_0_0_reg_163 );

    SC_METHOD(thread_zext_ln1116_4_fu_447_p1);
    sensitive << ( add_ln1116_2_reg_636 );

    SC_METHOD(thread_zext_ln1116_fu_246_p1);
    sensitive << ( x_0_0_0_reg_152 );

    SC_METHOD(thread_zext_ln1117_4_fu_375_p1);
    sensitive << ( c_0_0_0_reg_196 );

    SC_METHOD(thread_zext_ln1117_5_fu_384_p1);
    sensitive << ( add_ln1117_fu_379_p2 );

    SC_METHOD(thread_zext_ln1117_6_fu_396_p1);
    sensitive << ( tmp_12_fu_388_p3 );

    SC_METHOD(thread_zext_ln1117_7_fu_443_p1);
    sensitive << ( add_ln1117_4_reg_631 );

    SC_METHOD(thread_zext_ln1117_fu_371_p1);
    sensitive << ( c_0_0_0_reg_196 );

    SC_METHOD(thread_zext_ln1265_fu_355_p1);
    sensitive << ( tmp_2_fu_347_p3 );

    SC_METHOD(thread_zext_ln154_fu_321_p1);
    sensitive << ( k_0_0_0_reg_185 );

    SC_METHOD(thread_zext_ln158_1_fu_342_p1);
    sensitive << ( add_ln158_fu_337_p2 );

    SC_METHOD(thread_zext_ln158_fu_242_p1);
    sensitive << ( x_0_0_0_reg_152 );

    SC_METHOD(thread_zext_ln173_fu_496_p1);
    sensitive << ( k4_0_0_0_reg_218 );

    SC_METHOD(thread_zext_ln175_fu_517_p1);
    sensitive << ( add_ln175_fu_512_p2 );

    SC_METHOD(thread_zext_ln176_fu_534_p1);
    sensitive << ( k4_0_0_0_reg_218 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln148_fu_230_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln150_fu_268_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln152_fu_301_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln154_fu_325_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln156_fu_359_p2 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( icmp_ln171_fu_476_p2 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( icmp_ln173_fu_500_p2 );

    ap_CS_fsm = "00000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "conv3_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, out_0_0_V_address0, "(port)out_0_0_V_address0");
    sc_trace(mVcdFile, out_0_0_V_ce0, "(port)out_0_0_V_ce0");
    sc_trace(mVcdFile, out_0_0_V_we0, "(port)out_0_0_V_we0");
    sc_trace(mVcdFile, out_0_0_V_d0, "(port)out_0_0_V_d0");
    sc_trace(mVcdFile, out_0_0_V_q0, "(port)out_0_0_V_q0");
    sc_trace(mVcdFile, P2_out_V_address0, "(port)P2_out_V_address0");
    sc_trace(mVcdFile, P2_out_V_ce0, "(port)P2_out_V_ce0");
    sc_trace(mVcdFile, P2_out_V_q0, "(port)P2_out_V_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, K3_W_V_address0, "K3_W_V_address0");
    sc_trace(mVcdFile, K3_W_V_ce0, "K3_W_V_ce0");
    sc_trace(mVcdFile, K3_W_V_q0, "K3_W_V_q0");
    sc_trace(mVcdFile, K3_B_V_address0, "K3_B_V_address0");
    sc_trace(mVcdFile, K3_B_V_ce0, "K3_B_V_ce0");
    sc_trace(mVcdFile, K3_B_V_q0, "K3_B_V_q0");
    sc_trace(mVcdFile, add_ln148_fu_236_p2, "add_ln148_fu_236_p2");
    sc_trace(mVcdFile, add_ln148_reg_559, "add_ln148_reg_559");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, zext_ln158_fu_242_p1, "zext_ln158_fu_242_p1");
    sc_trace(mVcdFile, zext_ln158_reg_564, "zext_ln158_reg_564");
    sc_trace(mVcdFile, icmp_ln148_fu_230_p2, "icmp_ln148_fu_230_p2");
    sc_trace(mVcdFile, add_ln1116_fu_262_p2, "add_ln1116_fu_262_p2");
    sc_trace(mVcdFile, add_ln1116_reg_569, "add_ln1116_reg_569");
    sc_trace(mVcdFile, add_ln150_fu_274_p2, "add_ln150_fu_274_p2");
    sc_trace(mVcdFile, add_ln150_reg_577, "add_ln150_reg_577");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, zext_ln1116_2_fu_280_p1, "zext_ln1116_2_fu_280_p1");
    sc_trace(mVcdFile, zext_ln1116_2_reg_582, "zext_ln1116_2_reg_582");
    sc_trace(mVcdFile, icmp_ln150_fu_268_p2, "icmp_ln150_fu_268_p2");
    sc_trace(mVcdFile, tmp_19_cast_fu_293_p3, "tmp_19_cast_fu_293_p3");
    sc_trace(mVcdFile, tmp_19_cast_reg_587, "tmp_19_cast_reg_587");
    sc_trace(mVcdFile, add_ln152_fu_307_p2, "add_ln152_fu_307_p2");
    sc_trace(mVcdFile, add_ln152_reg_595, "add_ln152_reg_595");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, shl_ln1_fu_313_p3, "shl_ln1_fu_313_p3");
    sc_trace(mVcdFile, shl_ln1_reg_600, "shl_ln1_reg_600");
    sc_trace(mVcdFile, icmp_ln152_fu_301_p2, "icmp_ln152_fu_301_p2");
    sc_trace(mVcdFile, add_ln154_fu_331_p2, "add_ln154_fu_331_p2");
    sc_trace(mVcdFile, add_ln154_reg_608, "add_ln154_reg_608");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, zext_ln1265_fu_355_p1, "zext_ln1265_fu_355_p1");
    sc_trace(mVcdFile, zext_ln1265_reg_613, "zext_ln1265_reg_613");
    sc_trace(mVcdFile, icmp_ln154_fu_325_p2, "icmp_ln154_fu_325_p2");
    sc_trace(mVcdFile, out_0_0_V_addr_2_reg_618, "out_0_0_V_addr_2_reg_618");
    sc_trace(mVcdFile, add_ln156_fu_365_p2, "add_ln156_fu_365_p2");
    sc_trace(mVcdFile, add_ln156_reg_626, "add_ln156_reg_626");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, add_ln1117_4_fu_433_p2, "add_ln1117_4_fu_433_p2");
    sc_trace(mVcdFile, add_ln1117_4_reg_631, "add_ln1117_4_reg_631");
    sc_trace(mVcdFile, icmp_ln156_fu_359_p2, "icmp_ln156_fu_359_p2");
    sc_trace(mVcdFile, add_ln1116_2_fu_438_p2, "add_ln1116_2_fu_438_p2");
    sc_trace(mVcdFile, add_ln1116_2_reg_636, "add_ln1116_2_reg_636");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, trunc_ln_reg_651, "trunc_ln_reg_651");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, add_ln171_fu_482_p2, "add_ln171_fu_482_p2");
    sc_trace(mVcdFile, add_ln171_reg_659, "add_ln171_reg_659");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, shl_ln_fu_488_p3, "shl_ln_fu_488_p3");
    sc_trace(mVcdFile, shl_ln_reg_664, "shl_ln_reg_664");
    sc_trace(mVcdFile, icmp_ln171_fu_476_p2, "icmp_ln171_fu_476_p2");
    sc_trace(mVcdFile, add_ln173_fu_506_p2, "add_ln173_fu_506_p2");
    sc_trace(mVcdFile, add_ln173_reg_672, "add_ln173_reg_672");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, out_0_0_V_addr_reg_677, "out_0_0_V_addr_reg_677");
    sc_trace(mVcdFile, icmp_ln173_fu_500_p2, "icmp_ln173_fu_500_p2");
    sc_trace(mVcdFile, out_0_0_V_addr_1_reg_687, "out_0_0_V_addr_1_reg_687");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, x_0_0_0_reg_152, "x_0_0_0_reg_152");
    sc_trace(mVcdFile, y_0_0_0_reg_163, "y_0_0_0_reg_163");
    sc_trace(mVcdFile, set_0_0_0_reg_174, "set_0_0_0_reg_174");
    sc_trace(mVcdFile, k_0_0_0_reg_185, "k_0_0_0_reg_185");
    sc_trace(mVcdFile, c_0_0_0_reg_196, "c_0_0_0_reg_196");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, set3_0_0_0_reg_207, "set3_0_0_0_reg_207");
    sc_trace(mVcdFile, k4_0_0_0_reg_218, "k4_0_0_0_reg_218");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, zext_ln158_1_fu_342_p1, "zext_ln158_1_fu_342_p1");
    sc_trace(mVcdFile, zext_ln1117_7_fu_443_p1, "zext_ln1117_7_fu_443_p1");
    sc_trace(mVcdFile, zext_ln1116_4_fu_447_p1, "zext_ln1116_4_fu_447_p1");
    sc_trace(mVcdFile, zext_ln175_fu_517_p1, "zext_ln175_fu_517_p1");
    sc_trace(mVcdFile, zext_ln176_fu_534_p1, "zext_ln176_fu_534_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, add_ln703_fu_527_p2, "add_ln703_fu_527_p2");
    sc_trace(mVcdFile, tmp_11_fu_539_p3, "tmp_11_fu_539_p3");
    sc_trace(mVcdFile, tmp_s_fu_250_p3, "tmp_s_fu_250_p3");
    sc_trace(mVcdFile, zext_ln1116_fu_246_p1, "zext_ln1116_fu_246_p1");
    sc_trace(mVcdFile, zext_ln1116_1_fu_258_p1, "zext_ln1116_1_fu_258_p1");
    sc_trace(mVcdFile, zext_ln1116_3_fu_284_p1, "zext_ln1116_3_fu_284_p1");
    sc_trace(mVcdFile, add_ln1116_1_fu_288_p2, "add_ln1116_1_fu_288_p2");
    sc_trace(mVcdFile, zext_ln154_fu_321_p1, "zext_ln154_fu_321_p1");
    sc_trace(mVcdFile, add_ln158_fu_337_p2, "add_ln158_fu_337_p2");
    sc_trace(mVcdFile, tmp_2_fu_347_p3, "tmp_2_fu_347_p3");
    sc_trace(mVcdFile, zext_ln1117_4_fu_375_p1, "zext_ln1117_4_fu_375_p1");
    sc_trace(mVcdFile, add_ln1117_fu_379_p2, "add_ln1117_fu_379_p2");
    sc_trace(mVcdFile, tmp_12_fu_388_p3, "tmp_12_fu_388_p3");
    sc_trace(mVcdFile, zext_ln1117_5_fu_384_p1, "zext_ln1117_5_fu_384_p1");
    sc_trace(mVcdFile, zext_ln1117_6_fu_396_p1, "zext_ln1117_6_fu_396_p1");
    sc_trace(mVcdFile, add_ln1117_1_fu_400_p2, "add_ln1117_1_fu_400_p2");
    sc_trace(mVcdFile, add_ln1117_2_fu_406_p2, "add_ln1117_2_fu_406_p2");
    sc_trace(mVcdFile, trunc_ln1117_1_fu_415_p1, "trunc_ln1117_1_fu_415_p1");
    sc_trace(mVcdFile, trunc_ln1117_fu_411_p1, "trunc_ln1117_fu_411_p1");
    sc_trace(mVcdFile, p_shl1_cast_fu_419_p3, "p_shl1_cast_fu_419_p3");
    sc_trace(mVcdFile, add_ln1117_3_fu_427_p2, "add_ln1117_3_fu_427_p2");
    sc_trace(mVcdFile, zext_ln1117_fu_371_p1, "zext_ln1117_fu_371_p1");
    sc_trace(mVcdFile, grp_fu_547_p3, "grp_fu_547_p3");
    sc_trace(mVcdFile, zext_ln173_fu_496_p1, "zext_ln173_fu_496_p1");
    sc_trace(mVcdFile, add_ln175_fu_512_p2, "add_ln175_fu_512_p2");
    sc_trace(mVcdFile, sext_ln1265_fu_523_p1, "sext_ln1265_fu_523_p1");
    sc_trace(mVcdFile, grp_fu_547_p2, "grp_fu_547_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

conv3::~conv3() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete K3_W_V_U;
    delete K3_B_V_U;
    delete lenet_mac_muladd_eOg_U19;
}

void conv3::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        c_0_0_0_reg_196 = add_ln156_reg_626.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln154_fu_325_p2.read()))) {
        c_0_0_0_reg_196 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln171_fu_476_p2.read()))) {
        k4_0_0_0_reg_218 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        k4_0_0_0_reg_218 = add_ln173_reg_672.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(icmp_ln156_fu_359_p2.read(), ap_const_lv1_1))) {
        k_0_0_0_reg_185 = add_ln154_reg_608.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln152_fu_301_p2.read()))) {
        k_0_0_0_reg_185 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
         esl_seteq<1,1,1>(icmp_ln173_fu_500_p2.read(), ap_const_lv1_1))) {
        set3_0_0_0_reg_207 = add_ln171_reg_659.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln148_fu_230_p2.read(), ap_const_lv1_1))) {
        set3_0_0_0_reg_207 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln150_fu_268_p2.read()))) {
        set_0_0_0_reg_174 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(icmp_ln154_fu_325_p2.read(), ap_const_lv1_1))) {
        set_0_0_0_reg_174 = add_ln152_reg_595.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln150_fu_268_p2.read(), ap_const_lv1_1))) {
        x_0_0_0_reg_152 = add_ln148_reg_559.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        x_0_0_0_reg_152 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln152_fu_301_p2.read(), ap_const_lv1_1))) {
        y_0_0_0_reg_163 = add_ln150_reg_577.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln148_fu_230_p2.read(), ap_const_lv1_0))) {
        y_0_0_0_reg_163 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln156_fu_359_p2.read()))) {
        add_ln1116_2_reg_636 = add_ln1116_2_fu_438_p2.read();
        add_ln1117_4_reg_631 = add_ln1117_4_fu_433_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln148_fu_230_p2.read(), ap_const_lv1_0))) {
        add_ln1116_reg_569 = add_ln1116_fu_262_p2.read();
        zext_ln158_reg_564 = zext_ln158_fu_242_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        add_ln148_reg_559 = add_ln148_fu_236_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        add_ln150_reg_577 = add_ln150_fu_274_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        add_ln152_reg_595 = add_ln152_fu_307_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        add_ln154_reg_608 = add_ln154_fu_331_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        add_ln156_reg_626 = add_ln156_fu_365_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        add_ln171_reg_659 = add_ln171_fu_482_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        add_ln173_reg_672 = add_ln173_fu_506_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        out_0_0_V_addr_1_reg_687 =  (sc_lv<7>) (zext_ln176_fu_534_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln154_fu_325_p2.read()))) {
        out_0_0_V_addr_2_reg_618 =  (sc_lv<7>) (zext_ln158_1_fu_342_p1.read());
        zext_ln1265_reg_613 = zext_ln1265_fu_355_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln173_fu_500_p2.read()))) {
        out_0_0_V_addr_reg_677 =  (sc_lv<7>) (zext_ln175_fu_517_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln152_fu_301_p2.read()))) {
        shl_ln1_reg_600 = shl_ln1_fu_313_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln171_fu_476_p2.read()))) {
        shl_ln_reg_664 = shl_ln_fu_488_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln150_fu_268_p2.read()))) {
        tmp_19_cast_reg_587 = tmp_19_cast_fu_293_p3.read();
        zext_ln1116_2_reg_582 = zext_ln1116_2_fu_280_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        trunc_ln_reg_651 = grp_fu_547_p3.read().range(25, 10);
    }
}

void conv3::thread_K3_B_V_address0() {
    K3_B_V_address0 =  (sc_lv<7>) (zext_ln175_fu_517_p1.read());
}

void conv3::thread_K3_B_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        K3_B_V_ce0 = ap_const_logic_1;
    } else {
        K3_B_V_ce0 = ap_const_logic_0;
    }
}

void conv3::thread_K3_W_V_address0() {
    K3_W_V_address0 =  (sc_lv<16>) (zext_ln1117_7_fu_443_p1.read());
}

void conv3::thread_K3_W_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        K3_W_V_ce0 = ap_const_logic_1;
    } else {
        K3_W_V_ce0 = ap_const_logic_0;
    }
}

void conv3::thread_P2_out_V_address0() {
    P2_out_V_address0 =  (sc_lv<9>) (zext_ln1116_4_fu_447_p1.read());
}

void conv3::thread_P2_out_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        P2_out_V_ce0 = ap_const_logic_1;
    } else {
        P2_out_V_ce0 = ap_const_logic_0;
    }
}

void conv3::thread_add_ln1116_1_fu_288_p2() {
    add_ln1116_1_fu_288_p2 = (!zext_ln1116_3_fu_284_p1.read().is_01() || !add_ln1116_reg_569.read().is_01())? sc_lv<6>(): (sc_biguint<6>(zext_ln1116_3_fu_284_p1.read()) + sc_biguint<6>(add_ln1116_reg_569.read()));
}

void conv3::thread_add_ln1116_2_fu_438_p2() {
    add_ln1116_2_fu_438_p2 = (!tmp_19_cast_reg_587.read().is_01() || !zext_ln1117_fu_371_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(tmp_19_cast_reg_587.read()) + sc_biguint<10>(zext_ln1117_fu_371_p1.read()));
}

void conv3::thread_add_ln1116_fu_262_p2() {
    add_ln1116_fu_262_p2 = (!zext_ln1116_fu_246_p1.read().is_01() || !zext_ln1116_1_fu_258_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(zext_ln1116_fu_246_p1.read()) + sc_biguint<6>(zext_ln1116_1_fu_258_p1.read()));
}

void conv3::thread_add_ln1117_1_fu_400_p2() {
    add_ln1117_1_fu_400_p2 = (!zext_ln1117_5_fu_384_p1.read().is_01() || !zext_ln1117_6_fu_396_p1.read().is_01())? sc_lv<64>(): (sc_biguint<64>(zext_ln1117_5_fu_384_p1.read()) + sc_biguint<64>(zext_ln1117_6_fu_396_p1.read()));
}

void conv3::thread_add_ln1117_2_fu_406_p2() {
    add_ln1117_2_fu_406_p2 = (!add_ln1117_1_fu_400_p2.read().is_01() || !zext_ln158_reg_564.read().is_01())? sc_lv<64>(): (sc_biguint<64>(add_ln1117_1_fu_400_p2.read()) + sc_biguint<64>(zext_ln158_reg_564.read()));
}

void conv3::thread_add_ln1117_3_fu_427_p2() {
    add_ln1117_3_fu_427_p2 = (!trunc_ln1117_fu_411_p1.read().is_01() || !p_shl1_cast_fu_419_p3.read().is_01())? sc_lv<17>(): (sc_biguint<17>(trunc_ln1117_fu_411_p1.read()) + sc_biguint<17>(p_shl1_cast_fu_419_p3.read()));
}

void conv3::thread_add_ln1117_4_fu_433_p2() {
    add_ln1117_4_fu_433_p2 = (!add_ln1117_3_fu_427_p2.read().is_01() || !zext_ln1116_2_reg_582.read().is_01())? sc_lv<17>(): (sc_biguint<17>(add_ln1117_3_fu_427_p2.read()) + sc_biguint<17>(zext_ln1116_2_reg_582.read()));
}

void conv3::thread_add_ln1117_fu_379_p2() {
    add_ln1117_fu_379_p2 = (!zext_ln1265_reg_613.read().is_01() || !zext_ln1117_4_fu_375_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(zext_ln1265_reg_613.read()) + sc_biguint<12>(zext_ln1117_4_fu_375_p1.read()));
}

void conv3::thread_add_ln148_fu_236_p2() {
    add_ln148_fu_236_p2 = (!x_0_0_0_reg_152.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(x_0_0_0_reg_152.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void conv3::thread_add_ln150_fu_274_p2() {
    add_ln150_fu_274_p2 = (!y_0_0_0_reg_163.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(y_0_0_0_reg_163.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void conv3::thread_add_ln152_fu_307_p2() {
    add_ln152_fu_307_p2 = (!set_0_0_0_reg_174.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(set_0_0_0_reg_174.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void conv3::thread_add_ln154_fu_331_p2() {
    add_ln154_fu_331_p2 = (!k_0_0_0_reg_185.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(k_0_0_0_reg_185.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void conv3::thread_add_ln156_fu_365_p2() {
    add_ln156_fu_365_p2 = (!c_0_0_0_reg_196.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(c_0_0_0_reg_196.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void conv3::thread_add_ln158_fu_337_p2() {
    add_ln158_fu_337_p2 = (!shl_ln1_reg_600.read().is_01() || !zext_ln154_fu_321_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(shl_ln1_reg_600.read()) + sc_biguint<7>(zext_ln154_fu_321_p1.read()));
}

void conv3::thread_add_ln171_fu_482_p2() {
    add_ln171_fu_482_p2 = (!set3_0_0_0_reg_207.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(set3_0_0_0_reg_207.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void conv3::thread_add_ln173_fu_506_p2() {
    add_ln173_fu_506_p2 = (!k4_0_0_0_reg_218.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(k4_0_0_0_reg_218.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void conv3::thread_add_ln175_fu_512_p2() {
    add_ln175_fu_512_p2 = (!shl_ln_reg_664.read().is_01() || !zext_ln173_fu_496_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(shl_ln_reg_664.read()) + sc_biguint<7>(zext_ln173_fu_496_p1.read()));
}

void conv3::thread_add_ln703_fu_527_p2() {
    add_ln703_fu_527_p2 = (!out_0_0_V_q0.read().is_01() || !sext_ln1265_fu_523_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(out_0_0_V_q0.read()) + sc_bigint<16>(sext_ln1265_fu_523_p1.read()));
}

void conv3::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void conv3::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void conv3::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void conv3::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void conv3::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void conv3::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void conv3::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void conv3::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void conv3::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void conv3::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void conv3::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void conv3::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void conv3::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void conv3::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void conv3::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
          esl_seteq<1,1,1>(icmp_ln171_fu_476_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void conv3::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void conv3::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
         esl_seteq<1,1,1>(icmp_ln171_fu_476_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void conv3::thread_grp_fu_547_p2() {
    grp_fu_547_p2 = esl_concat<16,10>(out_0_0_V_q0.read(), ap_const_lv10_0);
}

void conv3::thread_icmp_ln148_fu_230_p2() {
    icmp_ln148_fu_230_p2 = (!x_0_0_0_reg_152.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(x_0_0_0_reg_152.read() == ap_const_lv3_5);
}

void conv3::thread_icmp_ln150_fu_268_p2() {
    icmp_ln150_fu_268_p2 = (!y_0_0_0_reg_163.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(y_0_0_0_reg_163.read() == ap_const_lv3_5);
}

void conv3::thread_icmp_ln152_fu_301_p2() {
    icmp_ln152_fu_301_p2 = (!set_0_0_0_reg_174.read().is_01() || !ap_const_lv4_F.is_01())? sc_lv<1>(): sc_lv<1>(set_0_0_0_reg_174.read() == ap_const_lv4_F);
}

void conv3::thread_icmp_ln154_fu_325_p2() {
    icmp_ln154_fu_325_p2 = (!k_0_0_0_reg_185.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(k_0_0_0_reg_185.read() == ap_const_lv4_8);
}

void conv3::thread_icmp_ln156_fu_359_p2() {
    icmp_ln156_fu_359_p2 = (!c_0_0_0_reg_196.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(c_0_0_0_reg_196.read() == ap_const_lv5_10);
}

void conv3::thread_icmp_ln171_fu_476_p2() {
    icmp_ln171_fu_476_p2 = (!set3_0_0_0_reg_207.read().is_01() || !ap_const_lv4_F.is_01())? sc_lv<1>(): sc_lv<1>(set3_0_0_0_reg_207.read() == ap_const_lv4_F);
}

void conv3::thread_icmp_ln173_fu_500_p2() {
    icmp_ln173_fu_500_p2 = (!k4_0_0_0_reg_218.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(k4_0_0_0_reg_218.read() == ap_const_lv4_8);
}

void conv3::thread_out_0_0_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        out_0_0_V_address0 = out_0_0_V_addr_1_reg_687.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        out_0_0_V_address0 =  (sc_lv<7>) (zext_ln176_fu_534_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        out_0_0_V_address0 = out_0_0_V_addr_reg_677.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        out_0_0_V_address0 =  (sc_lv<7>) (zext_ln175_fu_517_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        out_0_0_V_address0 = out_0_0_V_addr_2_reg_618.read();
    } else {
        out_0_0_V_address0 = "XXXXXXX";
    }
}

void conv3::thread_out_0_0_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        out_0_0_V_ce0 = ap_const_logic_1;
    } else {
        out_0_0_V_ce0 = ap_const_logic_0;
    }
}

void conv3::thread_out_0_0_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        out_0_0_V_d0 = ap_const_lv16_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        out_0_0_V_d0 = add_ln703_fu_527_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        out_0_0_V_d0 = trunc_ln_reg_651.read();
    } else {
        out_0_0_V_d0 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void conv3::thread_out_0_0_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_11_fu_539_p3.read())))) {
        out_0_0_V_we0 = ap_const_logic_1;
    } else {
        out_0_0_V_we0 = ap_const_logic_0;
    }
}

void conv3::thread_p_shl1_cast_fu_419_p3() {
    p_shl1_cast_fu_419_p3 = esl_concat<15,2>(trunc_ln1117_1_fu_415_p1.read(), ap_const_lv2_0);
}

void conv3::thread_sext_ln1265_fu_523_p1() {
    sext_ln1265_fu_523_p1 = esl_sext<16,8>(K3_B_V_q0.read());
}

void conv3::thread_shl_ln1_fu_313_p3() {
    shl_ln1_fu_313_p3 = esl_concat<4,3>(set_0_0_0_reg_174.read(), ap_const_lv3_0);
}

void conv3::thread_shl_ln_fu_488_p3() {
    shl_ln_fu_488_p3 = esl_concat<4,3>(set3_0_0_0_reg_207.read(), ap_const_lv3_0);
}

void conv3::thread_tmp_11_fu_539_p3() {
    tmp_11_fu_539_p3 = out_0_0_V_q0.read().range(15, 15);
}

void conv3::thread_tmp_12_fu_388_p3() {
    tmp_12_fu_388_p3 = esl_concat<12,2>(add_ln1117_fu_379_p2.read(), ap_const_lv2_0);
}

void conv3::thread_tmp_19_cast_fu_293_p3() {
    tmp_19_cast_fu_293_p3 = esl_concat<6,4>(add_ln1116_1_fu_288_p2.read(), ap_const_lv4_0);
}

void conv3::thread_tmp_2_fu_347_p3() {
    tmp_2_fu_347_p3 = esl_concat<7,4>(add_ln158_fu_337_p2.read(), ap_const_lv4_0);
}

void conv3::thread_tmp_s_fu_250_p3() {
    tmp_s_fu_250_p3 = esl_concat<3,2>(x_0_0_0_reg_152.read(), ap_const_lv2_0);
}

void conv3::thread_trunc_ln1117_1_fu_415_p1() {
    trunc_ln1117_1_fu_415_p1 = add_ln1117_2_fu_406_p2.read().range(15-1, 0);
}

void conv3::thread_trunc_ln1117_fu_411_p1() {
    trunc_ln1117_fu_411_p1 = add_ln1117_2_fu_406_p2.read().range(17-1, 0);
}

void conv3::thread_zext_ln1116_1_fu_258_p1() {
    zext_ln1116_1_fu_258_p1 = esl_zext<6,5>(tmp_s_fu_250_p3.read());
}

void conv3::thread_zext_ln1116_2_fu_280_p1() {
    zext_ln1116_2_fu_280_p1 = esl_zext<17,3>(y_0_0_0_reg_163.read());
}

void conv3::thread_zext_ln1116_3_fu_284_p1() {
    zext_ln1116_3_fu_284_p1 = esl_zext<6,3>(y_0_0_0_reg_163.read());
}

void conv3::thread_zext_ln1116_4_fu_447_p1() {
    zext_ln1116_4_fu_447_p1 = esl_zext<64,10>(add_ln1116_2_reg_636.read());
}

void conv3::thread_zext_ln1116_fu_246_p1() {
    zext_ln1116_fu_246_p1 = esl_zext<6,3>(x_0_0_0_reg_152.read());
}

void conv3::thread_zext_ln1117_4_fu_375_p1() {
    zext_ln1117_4_fu_375_p1 = esl_zext<12,5>(c_0_0_0_reg_196.read());
}

void conv3::thread_zext_ln1117_5_fu_384_p1() {
    zext_ln1117_5_fu_384_p1 = esl_zext<64,12>(add_ln1117_fu_379_p2.read());
}

void conv3::thread_zext_ln1117_6_fu_396_p1() {
    zext_ln1117_6_fu_396_p1 = esl_zext<64,14>(tmp_12_fu_388_p3.read());
}

void conv3::thread_zext_ln1117_7_fu_443_p1() {
    zext_ln1117_7_fu_443_p1 = esl_zext<64,17>(add_ln1117_4_reg_631.read());
}

void conv3::thread_zext_ln1117_fu_371_p1() {
    zext_ln1117_fu_371_p1 = esl_zext<10,5>(c_0_0_0_reg_196.read());
}

void conv3::thread_zext_ln1265_fu_355_p1() {
    zext_ln1265_fu_355_p1 = esl_zext<12,11>(tmp_2_fu_347_p3.read());
}

void conv3::thread_zext_ln154_fu_321_p1() {
    zext_ln154_fu_321_p1 = esl_zext<7,4>(k_0_0_0_reg_185.read());
}

void conv3::thread_zext_ln158_1_fu_342_p1() {
    zext_ln158_1_fu_342_p1 = esl_zext<64,7>(add_ln158_fu_337_p2.read());
}

void conv3::thread_zext_ln158_fu_242_p1() {
    zext_ln158_fu_242_p1 = esl_zext<64,3>(x_0_0_0_reg_152.read());
}

void conv3::thread_zext_ln173_fu_496_p1() {
    zext_ln173_fu_496_p1 = esl_zext<7,4>(k4_0_0_0_reg_218.read());
}

void conv3::thread_zext_ln175_fu_517_p1() {
    zext_ln175_fu_517_p1 = esl_zext<64,7>(add_ln175_fu_512_p2.read());
}

void conv3::thread_zext_ln176_fu_534_p1() {
    zext_ln176_fu_534_p1 = esl_zext<64,4>(k4_0_0_0_reg_218.read());
}

void conv3::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln148_fu_230_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln150_fu_268_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln152_fu_301_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(icmp_ln154_fu_325_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(icmp_ln156_fu_359_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 512 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(icmp_ln171_fu_476_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        case 1024 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(icmp_ln173_fu_500_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_state12;
            }
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<14>) ("XXXXXXXXXXXXXX");
            break;
    }
}

}

