// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _lenet_HH_
#define _lenet_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "softmax.h"
#include "conv1.h"
#include "conv2.h"
#include "conv3.h"
#include "pool1.h"
#include "pool2.h"
#include "fc1.h"
#include "fc2.h"
#include "lenet_C1_out_V.h"
#include "lenet_P1_out_V.h"
#include "lenet_C2_out_V.h"
#include "lenet_P2_out_V.h"
#include "lenet_C3_out_V_0_0.h"
#include "lenet_FC1_out_V.h"
#include "lenet_FC2_out_V.h"
#include "lenet_Crtl_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_CRTL_ADDR_WIDTH = 4,
         unsigned int C_S_AXI_CRTL_DATA_WIDTH = 32>
struct lenet : public sc_module {
    // Port declarations 34
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_out< sc_lv<32> > input_r_Addr_A;
    sc_out< sc_logic > input_r_EN_A;
    sc_out< sc_lv<4> > input_r_WEN_A;
    sc_out< sc_lv<32> > input_r_Din_A;
    sc_in< sc_lv<32> > input_r_Dout_A;
    sc_out< sc_logic > input_r_Clk_A;
    sc_out< sc_logic > input_r_Rst_A;
    sc_out< sc_lv<32> > Cout_Addr_A;
    sc_out< sc_logic > Cout_EN_A;
    sc_out< sc_lv<4> > Cout_WEN_A;
    sc_out< sc_lv<32> > Cout_Din_A;
    sc_in< sc_lv<32> > Cout_Dout_A;
    sc_out< sc_logic > Cout_Clk_A;
    sc_out< sc_logic > Cout_Rst_A;
    sc_in< sc_logic > s_axi_Crtl_AWVALID;
    sc_out< sc_logic > s_axi_Crtl_AWREADY;
    sc_in< sc_uint<C_S_AXI_CRTL_ADDR_WIDTH> > s_axi_Crtl_AWADDR;
    sc_in< sc_logic > s_axi_Crtl_WVALID;
    sc_out< sc_logic > s_axi_Crtl_WREADY;
    sc_in< sc_uint<C_S_AXI_CRTL_DATA_WIDTH> > s_axi_Crtl_WDATA;
    sc_in< sc_uint<C_S_AXI_CRTL_DATA_WIDTH/8> > s_axi_Crtl_WSTRB;
    sc_in< sc_logic > s_axi_Crtl_ARVALID;
    sc_out< sc_logic > s_axi_Crtl_ARREADY;
    sc_in< sc_uint<C_S_AXI_CRTL_ADDR_WIDTH> > s_axi_Crtl_ARADDR;
    sc_out< sc_logic > s_axi_Crtl_RVALID;
    sc_in< sc_logic > s_axi_Crtl_RREADY;
    sc_out< sc_uint<C_S_AXI_CRTL_DATA_WIDTH> > s_axi_Crtl_RDATA;
    sc_out< sc_lv<2> > s_axi_Crtl_RRESP;
    sc_out< sc_logic > s_axi_Crtl_BVALID;
    sc_in< sc_logic > s_axi_Crtl_BREADY;
    sc_out< sc_lv<2> > s_axi_Crtl_BRESP;
    sc_out< sc_logic > interrupt;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    lenet(sc_module_name name);
    SC_HAS_PROCESS(lenet);

    ~lenet();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    lenet_C1_out_V* C1_out_V_U;
    lenet_P1_out_V* P1_out_V_U;
    lenet_C2_out_V* C2_out_V_U;
    lenet_P2_out_V* P2_out_V_U;
    lenet_C3_out_V_0_0* C3_out_V_0_0_U;
    lenet_C3_out_V_0_0* Re_out_V_U;
    lenet_FC1_out_V* FC1_out_V_U;
    lenet_FC2_out_V* FC2_out_V_U;
    lenet_Crtl_s_axi<C_S_AXI_CRTL_ADDR_WIDTH,C_S_AXI_CRTL_DATA_WIDTH>* lenet_Crtl_s_axi_U;
    softmax* grp_softmax_fu_124;
    conv1* grp_conv1_fu_132;
    conv2* grp_conv2_fu_144;
    conv3* grp_conv3_fu_156;
    pool1* grp_pool1_fu_168;
    pool2* grp_pool2_fu_176;
    fc1* grp_fc1_fu_184;
    fc2* grp_fc2_fu_196;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > ap_start;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_lv<17> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_lv<13> > C1_out_V_address0;
    sc_signal< sc_logic > C1_out_V_ce0;
    sc_signal< sc_logic > C1_out_V_we0;
    sc_signal< sc_lv<16> > C1_out_V_q0;
    sc_signal< sc_lv<11> > P1_out_V_address0;
    sc_signal< sc_logic > P1_out_V_ce0;
    sc_signal< sc_logic > P1_out_V_we0;
    sc_signal< sc_lv<16> > P1_out_V_q0;
    sc_signal< sc_lv<11> > C2_out_V_address0;
    sc_signal< sc_logic > C2_out_V_ce0;
    sc_signal< sc_logic > C2_out_V_we0;
    sc_signal< sc_lv<16> > C2_out_V_q0;
    sc_signal< sc_lv<9> > P2_out_V_address0;
    sc_signal< sc_logic > P2_out_V_ce0;
    sc_signal< sc_logic > P2_out_V_we0;
    sc_signal< sc_lv<16> > P2_out_V_q0;
    sc_signal< sc_lv<7> > C3_out_V_0_0_address0;
    sc_signal< sc_logic > C3_out_V_0_0_ce0;
    sc_signal< sc_logic > C3_out_V_0_0_we0;
    sc_signal< sc_lv<16> > C3_out_V_0_0_q0;
    sc_signal< sc_lv<7> > Re_out_V_address0;
    sc_signal< sc_logic > Re_out_V_ce0;
    sc_signal< sc_logic > Re_out_V_we0;
    sc_signal< sc_lv<16> > Re_out_V_q0;
    sc_signal< sc_lv<7> > FC1_out_V_address0;
    sc_signal< sc_logic > FC1_out_V_ce0;
    sc_signal< sc_logic > FC1_out_V_we0;
    sc_signal< sc_lv<16> > FC1_out_V_q0;
    sc_signal< sc_lv<4> > FC2_out_V_address0;
    sc_signal< sc_logic > FC2_out_V_ce0;
    sc_signal< sc_logic > FC2_out_V_we0;
    sc_signal< sc_lv<16> > FC2_out_V_q0;
    sc_signal< sc_lv<7> > m_fu_214_p2;
    sc_signal< sc_lv<7> > m_reg_228;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_lv<64> > zext_ln191_fu_220_p1;
    sc_signal< sc_lv<64> > zext_ln191_reg_233;
    sc_signal< sc_lv<1> > icmp_ln189_fu_208_p2;
    sc_signal< sc_logic > grp_softmax_fu_124_ap_start;
    sc_signal< sc_logic > grp_softmax_fu_124_ap_done;
    sc_signal< sc_logic > grp_softmax_fu_124_ap_idle;
    sc_signal< sc_logic > grp_softmax_fu_124_ap_ready;
    sc_signal< sc_lv<32> > grp_softmax_fu_124_out_r_Addr_A;
    sc_signal< sc_logic > grp_softmax_fu_124_out_r_EN_A;
    sc_signal< sc_lv<4> > grp_softmax_fu_124_out_r_WEN_A;
    sc_signal< sc_lv<32> > grp_softmax_fu_124_out_r_Din_A;
    sc_signal< sc_lv<4> > grp_softmax_fu_124_FC2_out_V_address0;
    sc_signal< sc_logic > grp_softmax_fu_124_FC2_out_V_ce0;
    sc_signal< sc_logic > grp_conv1_fu_132_ap_start;
    sc_signal< sc_logic > grp_conv1_fu_132_ap_done;
    sc_signal< sc_logic > grp_conv1_fu_132_ap_idle;
    sc_signal< sc_logic > grp_conv1_fu_132_ap_ready;
    sc_signal< sc_lv<32> > grp_conv1_fu_132_input_r_Addr_A;
    sc_signal< sc_logic > grp_conv1_fu_132_input_r_EN_A;
    sc_signal< sc_lv<4> > grp_conv1_fu_132_input_r_WEN_A;
    sc_signal< sc_lv<32> > grp_conv1_fu_132_input_r_Din_A;
    sc_signal< sc_lv<13> > grp_conv1_fu_132_out_V_address0;
    sc_signal< sc_logic > grp_conv1_fu_132_out_V_ce0;
    sc_signal< sc_logic > grp_conv1_fu_132_out_V_we0;
    sc_signal< sc_lv<16> > grp_conv1_fu_132_out_V_d0;
    sc_signal< sc_logic > grp_conv2_fu_144_ap_start;
    sc_signal< sc_logic > grp_conv2_fu_144_ap_done;
    sc_signal< sc_logic > grp_conv2_fu_144_ap_idle;
    sc_signal< sc_logic > grp_conv2_fu_144_ap_ready;
    sc_signal< sc_lv<11> > grp_conv2_fu_144_out_V_address0;
    sc_signal< sc_logic > grp_conv2_fu_144_out_V_ce0;
    sc_signal< sc_logic > grp_conv2_fu_144_out_V_we0;
    sc_signal< sc_lv<16> > grp_conv2_fu_144_out_V_d0;
    sc_signal< sc_lv<11> > grp_conv2_fu_144_P1_out_V_address0;
    sc_signal< sc_logic > grp_conv2_fu_144_P1_out_V_ce0;
    sc_signal< sc_logic > grp_conv3_fu_156_ap_start;
    sc_signal< sc_logic > grp_conv3_fu_156_ap_done;
    sc_signal< sc_logic > grp_conv3_fu_156_ap_idle;
    sc_signal< sc_logic > grp_conv3_fu_156_ap_ready;
    sc_signal< sc_lv<7> > grp_conv3_fu_156_out_0_0_V_address0;
    sc_signal< sc_logic > grp_conv3_fu_156_out_0_0_V_ce0;
    sc_signal< sc_logic > grp_conv3_fu_156_out_0_0_V_we0;
    sc_signal< sc_lv<16> > grp_conv3_fu_156_out_0_0_V_d0;
    sc_signal< sc_lv<9> > grp_conv3_fu_156_P2_out_V_address0;
    sc_signal< sc_logic > grp_conv3_fu_156_P2_out_V_ce0;
    sc_signal< sc_logic > grp_pool1_fu_168_ap_start;
    sc_signal< sc_logic > grp_pool1_fu_168_ap_done;
    sc_signal< sc_logic > grp_pool1_fu_168_ap_idle;
    sc_signal< sc_logic > grp_pool1_fu_168_ap_ready;
    sc_signal< sc_lv<11> > grp_pool1_fu_168_out_V_address0;
    sc_signal< sc_logic > grp_pool1_fu_168_out_V_ce0;
    sc_signal< sc_logic > grp_pool1_fu_168_out_V_we0;
    sc_signal< sc_lv<16> > grp_pool1_fu_168_out_V_d0;
    sc_signal< sc_lv<13> > grp_pool1_fu_168_C1_out_V_address0;
    sc_signal< sc_logic > grp_pool1_fu_168_C1_out_V_ce0;
    sc_signal< sc_logic > grp_pool2_fu_176_ap_start;
    sc_signal< sc_logic > grp_pool2_fu_176_ap_done;
    sc_signal< sc_logic > grp_pool2_fu_176_ap_idle;
    sc_signal< sc_logic > grp_pool2_fu_176_ap_ready;
    sc_signal< sc_lv<9> > grp_pool2_fu_176_out_V_address0;
    sc_signal< sc_logic > grp_pool2_fu_176_out_V_ce0;
    sc_signal< sc_logic > grp_pool2_fu_176_out_V_we0;
    sc_signal< sc_lv<16> > grp_pool2_fu_176_out_V_d0;
    sc_signal< sc_lv<11> > grp_pool2_fu_176_C2_out_V_address0;
    sc_signal< sc_logic > grp_pool2_fu_176_C2_out_V_ce0;
    sc_signal< sc_logic > grp_fc1_fu_184_ap_start;
    sc_signal< sc_logic > grp_fc1_fu_184_ap_done;
    sc_signal< sc_logic > grp_fc1_fu_184_ap_idle;
    sc_signal< sc_logic > grp_fc1_fu_184_ap_ready;
    sc_signal< sc_lv<7> > grp_fc1_fu_184_out_V_address0;
    sc_signal< sc_logic > grp_fc1_fu_184_out_V_ce0;
    sc_signal< sc_logic > grp_fc1_fu_184_out_V_we0;
    sc_signal< sc_lv<16> > grp_fc1_fu_184_out_V_d0;
    sc_signal< sc_lv<7> > grp_fc1_fu_184_Re_out_V_address0;
    sc_signal< sc_logic > grp_fc1_fu_184_Re_out_V_ce0;
    sc_signal< sc_logic > grp_fc2_fu_196_ap_start;
    sc_signal< sc_logic > grp_fc2_fu_196_ap_done;
    sc_signal< sc_logic > grp_fc2_fu_196_ap_idle;
    sc_signal< sc_logic > grp_fc2_fu_196_ap_ready;
    sc_signal< sc_lv<4> > grp_fc2_fu_196_out_V_address0;
    sc_signal< sc_logic > grp_fc2_fu_196_out_V_ce0;
    sc_signal< sc_logic > grp_fc2_fu_196_out_V_we0;
    sc_signal< sc_lv<16> > grp_fc2_fu_196_out_V_d0;
    sc_signal< sc_lv<7> > grp_fc2_fu_196_FC1_out_V_address0;
    sc_signal< sc_logic > grp_fc2_fu_196_FC1_out_V_ce0;
    sc_signal< sc_lv<7> > m_0_i_reg_113;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_logic > grp_softmax_fu_124_ap_start_reg;
    sc_signal< sc_logic > ap_CS_fsm_state16;
    sc_signal< sc_logic > ap_CS_fsm_state17;
    sc_signal< sc_logic > grp_conv1_fu_132_ap_start_reg;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > grp_conv2_fu_144_ap_start_reg;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_logic > grp_conv3_fu_156_ap_start_reg;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_logic > grp_pool1_fu_168_ap_start_reg;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_logic > grp_pool2_fu_176_ap_start_reg;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_logic > grp_fc1_fu_184_ap_start_reg;
    sc_signal< sc_logic > ap_CS_fsm_state13;
    sc_signal< sc_logic > grp_fc2_fu_196_ap_start_reg;
    sc_signal< sc_logic > ap_CS_fsm_state14;
    sc_signal< sc_logic > ap_CS_fsm_state15;
    sc_signal< sc_lv<17> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<17> ap_ST_fsm_state1;
    static const sc_lv<17> ap_ST_fsm_state2;
    static const sc_lv<17> ap_ST_fsm_state3;
    static const sc_lv<17> ap_ST_fsm_state4;
    static const sc_lv<17> ap_ST_fsm_state5;
    static const sc_lv<17> ap_ST_fsm_state6;
    static const sc_lv<17> ap_ST_fsm_state7;
    static const sc_lv<17> ap_ST_fsm_state8;
    static const sc_lv<17> ap_ST_fsm_state9;
    static const sc_lv<17> ap_ST_fsm_state10;
    static const sc_lv<17> ap_ST_fsm_state11;
    static const sc_lv<17> ap_ST_fsm_state12;
    static const sc_lv<17> ap_ST_fsm_state13;
    static const sc_lv<17> ap_ST_fsm_state14;
    static const sc_lv<17> ap_ST_fsm_state15;
    static const sc_lv<17> ap_ST_fsm_state16;
    static const sc_lv<17> ap_ST_fsm_state17;
    static const sc_lv<32> ap_const_lv32_0;
    static const int C_S_AXI_DATA_WIDTH;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<7> ap_const_lv7_0;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<7> ap_const_lv7_78;
    static const sc_lv<7> ap_const_lv7_1;
    static const sc_lv<4> ap_const_lv4_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_C1_out_V_address0();
    void thread_C1_out_V_ce0();
    void thread_C1_out_V_we0();
    void thread_C2_out_V_address0();
    void thread_C2_out_V_ce0();
    void thread_C2_out_V_we0();
    void thread_C3_out_V_0_0_address0();
    void thread_C3_out_V_0_0_ce0();
    void thread_C3_out_V_0_0_we0();
    void thread_Cout_Addr_A();
    void thread_Cout_Clk_A();
    void thread_Cout_Din_A();
    void thread_Cout_EN_A();
    void thread_Cout_Rst_A();
    void thread_Cout_WEN_A();
    void thread_FC1_out_V_address0();
    void thread_FC1_out_V_ce0();
    void thread_FC1_out_V_we0();
    void thread_FC2_out_V_address0();
    void thread_FC2_out_V_ce0();
    void thread_FC2_out_V_we0();
    void thread_P1_out_V_address0();
    void thread_P1_out_V_ce0();
    void thread_P1_out_V_we0();
    void thread_P2_out_V_address0();
    void thread_P2_out_V_ce0();
    void thread_P2_out_V_we0();
    void thread_Re_out_V_address0();
    void thread_Re_out_V_ce0();
    void thread_Re_out_V_we0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state14();
    void thread_ap_CS_fsm_state15();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state17();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_grp_conv1_fu_132_ap_start();
    void thread_grp_conv2_fu_144_ap_start();
    void thread_grp_conv3_fu_156_ap_start();
    void thread_grp_fc1_fu_184_ap_start();
    void thread_grp_fc2_fu_196_ap_start();
    void thread_grp_pool1_fu_168_ap_start();
    void thread_grp_pool2_fu_176_ap_start();
    void thread_grp_softmax_fu_124_ap_start();
    void thread_icmp_ln189_fu_208_p2();
    void thread_input_r_Addr_A();
    void thread_input_r_Clk_A();
    void thread_input_r_Din_A();
    void thread_input_r_EN_A();
    void thread_input_r_Rst_A();
    void thread_input_r_WEN_A();
    void thread_m_fu_214_p2();
    void thread_zext_ln191_fu_220_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
