// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "pool1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic pool1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic pool1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<7> pool1::ap_ST_fsm_state1 = "1";
const sc_lv<7> pool1::ap_ST_fsm_state2 = "10";
const sc_lv<7> pool1::ap_ST_fsm_state3 = "100";
const sc_lv<7> pool1::ap_ST_fsm_state4 = "1000";
const sc_lv<7> pool1::ap_ST_fsm_state5 = "10000";
const sc_lv<7> pool1::ap_ST_fsm_state6 = "100000";
const sc_lv<7> pool1::ap_ST_fsm_state7 = "1000000";
const sc_lv<32> pool1::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> pool1::ap_const_lv32_1 = "1";
const sc_lv<1> pool1::ap_const_lv1_0 = "0";
const sc_lv<32> pool1::ap_const_lv32_2 = "10";
const sc_lv<32> pool1::ap_const_lv32_3 = "11";
const sc_lv<32> pool1::ap_const_lv32_4 = "100";
const sc_lv<32> pool1::ap_const_lv32_5 = "101";
const sc_lv<32> pool1::ap_const_lv32_6 = "110";
const sc_lv<4> pool1::ap_const_lv4_0 = "0000";
const sc_lv<1> pool1::ap_const_lv1_1 = "1";
const sc_lv<3> pool1::ap_const_lv3_0 = "000";
const sc_lv<16> pool1::ap_const_lv16_0 = "0000000000000000";
const sc_lv<2> pool1::ap_const_lv2_0 = "00";
const sc_lv<4> pool1::ap_const_lv4_E = "1110";
const sc_lv<4> pool1::ap_const_lv4_1 = "1";
const sc_lv<3> pool1::ap_const_lv3_6 = "110";
const sc_lv<3> pool1::ap_const_lv3_1 = "1";
const sc_lv<2> pool1::ap_const_lv2_2 = "10";
const sc_lv<2> pool1::ap_const_lv2_1 = "1";
const sc_lv<5> pool1::ap_const_lv5_0 = "00000";
const bool pool1::ap_const_boolean_1 = true;

pool1::pool1(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_C1_out_V_address0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln1494_6_fu_424_p1 );

    SC_METHOD(thread_C1_out_V_ce0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_add_ln1494_3_fu_419_p2);
    sensitive << ( zext_ln203_8_reg_487 );
    sensitive << ( sub_ln1494_1_fu_413_p2 );

    SC_METHOD(thread_add_ln1494_fu_384_p2);
    sensitive << ( sext_ln1494_reg_505 );
    sensitive << ( zext_ln1494_5_fu_380_p1 );

    SC_METHOD(thread_add_ln203_3_fu_294_p2);
    sensitive << ( sub_ln203_1_reg_474 );
    sensitive << ( zext_ln203_9_fu_290_p1 );

    SC_METHOD(thread_add_ln203_fu_239_p2);
    sensitive << ( sext_ln203_reg_456 );
    sensitive << ( zext_ln203_7_fu_235_p1 );

    SC_METHOD(thread_add_ln61_1_fu_375_p2);
    sensitive << ( shl_ln61_1_reg_469 );
    sensitive << ( zext_ln59_fu_359_p1 );

    SC_METHOD(thread_add_ln61_fu_320_p2);
    sensitive << ( shl_ln_reg_451 );
    sensitive << ( zext_ln57_fu_304_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln50_fu_169_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln50_fu_169_p2 );

    SC_METHOD(thread_i_fu_175_p2);
    sensitive << ( i_0_reg_89 );

    SC_METHOD(thread_icmp_ln1494_fu_429_p2);
    sensitive << ( C1_out_V_q0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( p_07_2_reg_146 );

    SC_METHOD(thread_icmp_ln50_fu_169_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_89 );

    SC_METHOD(thread_icmp_ln52_fu_215_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( j_0_reg_100 );

    SC_METHOD(thread_icmp_ln54_fu_274_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( k_0_reg_111 );

    SC_METHOD(thread_icmp_ln57_fu_308_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( x_0_reg_135 );

    SC_METHOD(thread_icmp_ln59_fu_363_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( y_0_reg_158 );

    SC_METHOD(thread_j_fu_221_p2);
    sensitive << ( j_0_reg_100 );

    SC_METHOD(thread_k_fu_280_p2);
    sensitive << ( k_0_reg_111 );

    SC_METHOD(thread_out_V_address0);
    sensitive << ( out_V_addr_reg_492 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_out_V_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_out_V_d0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( p_07_1_reg_122 );

    SC_METHOD(thread_out_V_we0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln57_fu_308_p2 );

    SC_METHOD(thread_p_shl2_cast_fu_248_p3);
    sensitive << ( trunc_ln203_fu_244_p1 );

    SC_METHOD(thread_p_shl6_cast_fu_393_p3);
    sensitive << ( trunc_ln1494_fu_389_p1 );

    SC_METHOD(thread_select_ln61_fu_435_p3);
    sensitive << ( C1_out_V_q0 );
    sensitive << ( p_07_2_reg_146 );
    sensitive << ( icmp_ln1494_fu_429_p2 );

    SC_METHOD(thread_sext_ln1494_1_fu_409_p1);
    sensitive << ( tmp_9_fu_401_p3 );

    SC_METHOD(thread_sext_ln1494_fu_355_p1);
    sensitive << ( sub_ln1494_fu_349_p2 );

    SC_METHOD(thread_sext_ln203_1_fu_264_p1);
    sensitive << ( tmp_7_fu_256_p3 );

    SC_METHOD(thread_sext_ln203_fu_211_p1);
    sensitive << ( sub_ln203_fu_205_p2 );

    SC_METHOD(thread_shl_ln61_1_fu_227_p3);
    sensitive << ( j_0_reg_100 );

    SC_METHOD(thread_shl_ln_fu_181_p3);
    sensitive << ( i_0_reg_89 );

    SC_METHOD(thread_sub_ln1494_1_fu_413_p2);
    sensitive << ( p_shl6_cast_fu_393_p3 );
    sensitive << ( sext_ln1494_1_fu_409_p1 );

    SC_METHOD(thread_sub_ln1494_fu_349_p2);
    sensitive << ( zext_ln1494_fu_333_p1 );
    sensitive << ( zext_ln1494_4_fu_345_p1 );

    SC_METHOD(thread_sub_ln203_1_fu_268_p2);
    sensitive << ( p_shl2_cast_fu_248_p3 );
    sensitive << ( sext_ln203_1_fu_264_p1 );

    SC_METHOD(thread_sub_ln203_fu_205_p2);
    sensitive << ( zext_ln203_fu_197_p1 );
    sensitive << ( zext_ln203_6_fu_201_p1 );

    SC_METHOD(thread_tmp_1_fu_337_p3);
    sensitive << ( add_ln61_fu_320_p2 );

    SC_METHOD(thread_tmp_7_fu_256_p3);
    sensitive << ( add_ln203_fu_239_p2 );

    SC_METHOD(thread_tmp_8_fu_189_p3);
    sensitive << ( i_0_reg_89 );

    SC_METHOD(thread_tmp_9_fu_401_p3);
    sensitive << ( add_ln1494_fu_384_p2 );

    SC_METHOD(thread_tmp_s_fu_325_p3);
    sensitive << ( add_ln61_fu_320_p2 );

    SC_METHOD(thread_trunc_ln1494_fu_389_p1);
    sensitive << ( add_ln1494_fu_384_p2 );

    SC_METHOD(thread_trunc_ln203_fu_244_p1);
    sensitive << ( add_ln203_fu_239_p2 );

    SC_METHOD(thread_x_fu_314_p2);
    sensitive << ( x_0_reg_135 );

    SC_METHOD(thread_y_fu_369_p2);
    sensitive << ( y_0_reg_158 );

    SC_METHOD(thread_zext_ln1494_4_fu_345_p1);
    sensitive << ( tmp_1_fu_337_p3 );

    SC_METHOD(thread_zext_ln1494_5_fu_380_p1);
    sensitive << ( add_ln61_1_fu_375_p2 );

    SC_METHOD(thread_zext_ln1494_6_fu_424_p1);
    sensitive << ( add_ln1494_3_fu_419_p2 );

    SC_METHOD(thread_zext_ln1494_fu_333_p1);
    sensitive << ( tmp_s_fu_325_p3 );

    SC_METHOD(thread_zext_ln203_10_fu_299_p1);
    sensitive << ( add_ln203_3_fu_294_p2 );

    SC_METHOD(thread_zext_ln203_6_fu_201_p1);
    sensitive << ( shl_ln_fu_181_p3 );

    SC_METHOD(thread_zext_ln203_7_fu_235_p1);
    sensitive << ( j_0_reg_100 );

    SC_METHOD(thread_zext_ln203_8_fu_286_p1);
    sensitive << ( k_0_reg_111 );

    SC_METHOD(thread_zext_ln203_9_fu_290_p1);
    sensitive << ( k_0_reg_111 );

    SC_METHOD(thread_zext_ln203_fu_197_p1);
    sensitive << ( tmp_8_fu_189_p3 );

    SC_METHOD(thread_zext_ln57_fu_304_p1);
    sensitive << ( x_0_reg_135 );

    SC_METHOD(thread_zext_ln59_fu_359_p1);
    sensitive << ( y_0_reg_158 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln50_fu_169_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln52_fu_215_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln54_fu_274_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln57_fu_308_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln59_fu_363_p2 );

    ap_CS_fsm = "0000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "pool1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, out_V_address0, "(port)out_V_address0");
    sc_trace(mVcdFile, out_V_ce0, "(port)out_V_ce0");
    sc_trace(mVcdFile, out_V_we0, "(port)out_V_we0");
    sc_trace(mVcdFile, out_V_d0, "(port)out_V_d0");
    sc_trace(mVcdFile, C1_out_V_address0, "(port)C1_out_V_address0");
    sc_trace(mVcdFile, C1_out_V_ce0, "(port)C1_out_V_ce0");
    sc_trace(mVcdFile, C1_out_V_q0, "(port)C1_out_V_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, i_fu_175_p2, "i_fu_175_p2");
    sc_trace(mVcdFile, i_reg_446, "i_reg_446");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, shl_ln_fu_181_p3, "shl_ln_fu_181_p3");
    sc_trace(mVcdFile, shl_ln_reg_451, "shl_ln_reg_451");
    sc_trace(mVcdFile, icmp_ln50_fu_169_p2, "icmp_ln50_fu_169_p2");
    sc_trace(mVcdFile, sext_ln203_fu_211_p1, "sext_ln203_fu_211_p1");
    sc_trace(mVcdFile, sext_ln203_reg_456, "sext_ln203_reg_456");
    sc_trace(mVcdFile, j_fu_221_p2, "j_fu_221_p2");
    sc_trace(mVcdFile, j_reg_464, "j_reg_464");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, shl_ln61_1_fu_227_p3, "shl_ln61_1_fu_227_p3");
    sc_trace(mVcdFile, shl_ln61_1_reg_469, "shl_ln61_1_reg_469");
    sc_trace(mVcdFile, icmp_ln52_fu_215_p2, "icmp_ln52_fu_215_p2");
    sc_trace(mVcdFile, sub_ln203_1_fu_268_p2, "sub_ln203_1_fu_268_p2");
    sc_trace(mVcdFile, sub_ln203_1_reg_474, "sub_ln203_1_reg_474");
    sc_trace(mVcdFile, k_fu_280_p2, "k_fu_280_p2");
    sc_trace(mVcdFile, k_reg_482, "k_reg_482");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, zext_ln203_8_fu_286_p1, "zext_ln203_8_fu_286_p1");
    sc_trace(mVcdFile, zext_ln203_8_reg_487, "zext_ln203_8_reg_487");
    sc_trace(mVcdFile, icmp_ln54_fu_274_p2, "icmp_ln54_fu_274_p2");
    sc_trace(mVcdFile, out_V_addr_reg_492, "out_V_addr_reg_492");
    sc_trace(mVcdFile, x_fu_314_p2, "x_fu_314_p2");
    sc_trace(mVcdFile, x_reg_500, "x_reg_500");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, sext_ln1494_fu_355_p1, "sext_ln1494_fu_355_p1");
    sc_trace(mVcdFile, sext_ln1494_reg_505, "sext_ln1494_reg_505");
    sc_trace(mVcdFile, icmp_ln57_fu_308_p2, "icmp_ln57_fu_308_p2");
    sc_trace(mVcdFile, y_fu_369_p2, "y_fu_369_p2");
    sc_trace(mVcdFile, y_reg_513, "y_reg_513");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, icmp_ln59_fu_363_p2, "icmp_ln59_fu_363_p2");
    sc_trace(mVcdFile, select_ln61_fu_435_p3, "select_ln61_fu_435_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, i_0_reg_89, "i_0_reg_89");
    sc_trace(mVcdFile, j_0_reg_100, "j_0_reg_100");
    sc_trace(mVcdFile, k_0_reg_111, "k_0_reg_111");
    sc_trace(mVcdFile, p_07_1_reg_122, "p_07_1_reg_122");
    sc_trace(mVcdFile, x_0_reg_135, "x_0_reg_135");
    sc_trace(mVcdFile, p_07_2_reg_146, "p_07_2_reg_146");
    sc_trace(mVcdFile, y_0_reg_158, "y_0_reg_158");
    sc_trace(mVcdFile, zext_ln203_10_fu_299_p1, "zext_ln203_10_fu_299_p1");
    sc_trace(mVcdFile, zext_ln1494_6_fu_424_p1, "zext_ln1494_6_fu_424_p1");
    sc_trace(mVcdFile, tmp_8_fu_189_p3, "tmp_8_fu_189_p3");
    sc_trace(mVcdFile, zext_ln203_fu_197_p1, "zext_ln203_fu_197_p1");
    sc_trace(mVcdFile, zext_ln203_6_fu_201_p1, "zext_ln203_6_fu_201_p1");
    sc_trace(mVcdFile, sub_ln203_fu_205_p2, "sub_ln203_fu_205_p2");
    sc_trace(mVcdFile, zext_ln203_7_fu_235_p1, "zext_ln203_7_fu_235_p1");
    sc_trace(mVcdFile, add_ln203_fu_239_p2, "add_ln203_fu_239_p2");
    sc_trace(mVcdFile, trunc_ln203_fu_244_p1, "trunc_ln203_fu_244_p1");
    sc_trace(mVcdFile, tmp_7_fu_256_p3, "tmp_7_fu_256_p3");
    sc_trace(mVcdFile, p_shl2_cast_fu_248_p3, "p_shl2_cast_fu_248_p3");
    sc_trace(mVcdFile, sext_ln203_1_fu_264_p1, "sext_ln203_1_fu_264_p1");
    sc_trace(mVcdFile, zext_ln203_9_fu_290_p1, "zext_ln203_9_fu_290_p1");
    sc_trace(mVcdFile, add_ln203_3_fu_294_p2, "add_ln203_3_fu_294_p2");
    sc_trace(mVcdFile, zext_ln57_fu_304_p1, "zext_ln57_fu_304_p1");
    sc_trace(mVcdFile, add_ln61_fu_320_p2, "add_ln61_fu_320_p2");
    sc_trace(mVcdFile, tmp_s_fu_325_p3, "tmp_s_fu_325_p3");
    sc_trace(mVcdFile, tmp_1_fu_337_p3, "tmp_1_fu_337_p3");
    sc_trace(mVcdFile, zext_ln1494_fu_333_p1, "zext_ln1494_fu_333_p1");
    sc_trace(mVcdFile, zext_ln1494_4_fu_345_p1, "zext_ln1494_4_fu_345_p1");
    sc_trace(mVcdFile, sub_ln1494_fu_349_p2, "sub_ln1494_fu_349_p2");
    sc_trace(mVcdFile, zext_ln59_fu_359_p1, "zext_ln59_fu_359_p1");
    sc_trace(mVcdFile, add_ln61_1_fu_375_p2, "add_ln61_1_fu_375_p2");
    sc_trace(mVcdFile, zext_ln1494_5_fu_380_p1, "zext_ln1494_5_fu_380_p1");
    sc_trace(mVcdFile, add_ln1494_fu_384_p2, "add_ln1494_fu_384_p2");
    sc_trace(mVcdFile, trunc_ln1494_fu_389_p1, "trunc_ln1494_fu_389_p1");
    sc_trace(mVcdFile, tmp_9_fu_401_p3, "tmp_9_fu_401_p3");
    sc_trace(mVcdFile, p_shl6_cast_fu_393_p3, "p_shl6_cast_fu_393_p3");
    sc_trace(mVcdFile, sext_ln1494_1_fu_409_p1, "sext_ln1494_1_fu_409_p1");
    sc_trace(mVcdFile, sub_ln1494_1_fu_413_p2, "sub_ln1494_1_fu_413_p2");
    sc_trace(mVcdFile, add_ln1494_3_fu_419_p2, "add_ln1494_3_fu_419_p2");
    sc_trace(mVcdFile, icmp_ln1494_fu_429_p2, "icmp_ln1494_fu_429_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

pool1::~pool1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void pool1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln52_fu_215_p2.read(), ap_const_lv1_1))) {
        i_0_reg_89 = i_reg_446.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_89 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln50_fu_169_p2.read(), ap_const_lv1_0))) {
        j_0_reg_100 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(icmp_ln54_fu_274_p2.read(), ap_const_lv1_1))) {
        j_0_reg_100 = j_reg_464.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln57_fu_308_p2.read(), ap_const_lv1_1))) {
        k_0_reg_111 = k_reg_482.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln52_fu_215_p2.read()))) {
        k_0_reg_111 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(icmp_ln59_fu_363_p2.read(), ap_const_lv1_1))) {
        p_07_1_reg_122 = p_07_2_reg_146.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln54_fu_274_p2.read()))) {
        p_07_1_reg_122 = ap_const_lv16_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln57_fu_308_p2.read()))) {
        p_07_2_reg_146 = p_07_1_reg_122.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        p_07_2_reg_146 = select_ln61_fu_435_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(icmp_ln59_fu_363_p2.read(), ap_const_lv1_1))) {
        x_0_reg_135 = x_reg_500.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln54_fu_274_p2.read()))) {
        x_0_reg_135 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln57_fu_308_p2.read()))) {
        y_0_reg_158 = ap_const_lv2_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        y_0_reg_158 = y_reg_513.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_446 = i_fu_175_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        j_reg_464 = j_fu_221_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        k_reg_482 = k_fu_280_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln54_fu_274_p2.read()))) {
        out_V_addr_reg_492 =  (sc_lv<11>) (zext_ln203_10_fu_299_p1.read());
        zext_ln203_8_reg_487 = zext_ln203_8_fu_286_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln57_fu_308_p2.read()))) {
        sext_ln1494_reg_505 = sext_ln1494_fu_355_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln50_fu_169_p2.read(), ap_const_lv1_0))) {
        sext_ln203_reg_456 = sext_ln203_fu_211_p1.read();
        shl_ln_reg_451 = shl_ln_fu_181_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln52_fu_215_p2.read()))) {
        shl_ln61_1_reg_469 = shl_ln61_1_fu_227_p3.read();
        sub_ln203_1_reg_474 = sub_ln203_1_fu_268_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        x_reg_500 = x_fu_314_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        y_reg_513 = y_fu_369_p2.read();
    }
}

void pool1::thread_C1_out_V_address0() {
    C1_out_V_address0 =  (sc_lv<13>) (zext_ln1494_6_fu_424_p1.read());
}

void pool1::thread_C1_out_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        C1_out_V_ce0 = ap_const_logic_1;
    } else {
        C1_out_V_ce0 = ap_const_logic_0;
    }
}

void pool1::thread_add_ln1494_3_fu_419_p2() {
    add_ln1494_3_fu_419_p2 = (!sub_ln1494_1_fu_413_p2.read().is_01() || !zext_ln203_8_reg_487.read().is_01())? sc_lv<14>(): (sc_biguint<14>(sub_ln1494_1_fu_413_p2.read()) + sc_biguint<14>(zext_ln203_8_reg_487.read()));
}

void pool1::thread_add_ln1494_fu_384_p2() {
    add_ln1494_fu_384_p2 = (!sext_ln1494_reg_505.read().is_01() || !zext_ln1494_5_fu_380_p1.read().is_01())? sc_lv<12>(): (sc_bigint<12>(sext_ln1494_reg_505.read()) + sc_biguint<12>(zext_ln1494_5_fu_380_p1.read()));
}

void pool1::thread_add_ln203_3_fu_294_p2() {
    add_ln203_3_fu_294_p2 = (!sub_ln203_1_reg_474.read().is_01() || !zext_ln203_9_fu_290_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(sub_ln203_1_reg_474.read()) + sc_biguint<12>(zext_ln203_9_fu_290_p1.read()));
}

void pool1::thread_add_ln203_fu_239_p2() {
    add_ln203_fu_239_p2 = (!zext_ln203_7_fu_235_p1.read().is_01() || !sext_ln203_reg_456.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln203_7_fu_235_p1.read()) + sc_bigint<10>(sext_ln203_reg_456.read()));
}

void pool1::thread_add_ln61_1_fu_375_p2() {
    add_ln61_1_fu_375_p2 = (!zext_ln59_fu_359_p1.read().is_01() || !shl_ln61_1_reg_469.read().is_01())? sc_lv<5>(): (sc_biguint<5>(zext_ln59_fu_359_p1.read()) + sc_biguint<5>(shl_ln61_1_reg_469.read()));
}

void pool1::thread_add_ln61_fu_320_p2() {
    add_ln61_fu_320_p2 = (!zext_ln57_fu_304_p1.read().is_01() || !shl_ln_reg_451.read().is_01())? sc_lv<5>(): (sc_biguint<5>(zext_ln57_fu_304_p1.read()) + sc_biguint<5>(shl_ln_reg_451.read()));
}

void pool1::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void pool1::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void pool1::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void pool1::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void pool1::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void pool1::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void pool1::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void pool1::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln50_fu_169_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void pool1::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void pool1::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln50_fu_169_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void pool1::thread_i_fu_175_p2() {
    i_fu_175_p2 = (!i_0_reg_89.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_0_reg_89.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void pool1::thread_icmp_ln1494_fu_429_p2() {
    icmp_ln1494_fu_429_p2 = (!C1_out_V_q0.read().is_01() || !p_07_2_reg_146.read().is_01())? sc_lv<1>(): (sc_bigint<16>(C1_out_V_q0.read()) > sc_bigint<16>(p_07_2_reg_146.read()));
}

void pool1::thread_icmp_ln50_fu_169_p2() {
    icmp_ln50_fu_169_p2 = (!i_0_reg_89.read().is_01() || !ap_const_lv4_E.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_89.read() == ap_const_lv4_E);
}

void pool1::thread_icmp_ln52_fu_215_p2() {
    icmp_ln52_fu_215_p2 = (!j_0_reg_100.read().is_01() || !ap_const_lv4_E.is_01())? sc_lv<1>(): sc_lv<1>(j_0_reg_100.read() == ap_const_lv4_E);
}

void pool1::thread_icmp_ln54_fu_274_p2() {
    icmp_ln54_fu_274_p2 = (!k_0_reg_111.read().is_01() || !ap_const_lv3_6.is_01())? sc_lv<1>(): sc_lv<1>(k_0_reg_111.read() == ap_const_lv3_6);
}

void pool1::thread_icmp_ln57_fu_308_p2() {
    icmp_ln57_fu_308_p2 = (!x_0_reg_135.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(x_0_reg_135.read() == ap_const_lv2_2);
}

void pool1::thread_icmp_ln59_fu_363_p2() {
    icmp_ln59_fu_363_p2 = (!y_0_reg_158.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(y_0_reg_158.read() == ap_const_lv2_2);
}

void pool1::thread_j_fu_221_p2() {
    j_fu_221_p2 = (!j_0_reg_100.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(j_0_reg_100.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void pool1::thread_k_fu_280_p2() {
    k_fu_280_p2 = (!k_0_reg_111.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(k_0_reg_111.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void pool1::thread_out_V_address0() {
    out_V_address0 = out_V_addr_reg_492.read();
}

void pool1::thread_out_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        out_V_ce0 = ap_const_logic_1;
    } else {
        out_V_ce0 = ap_const_logic_0;
    }
}

void pool1::thread_out_V_d0() {
    out_V_d0 = p_07_1_reg_122.read();
}

void pool1::thread_out_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln57_fu_308_p2.read(), ap_const_lv1_1))) {
        out_V_we0 = ap_const_logic_1;
    } else {
        out_V_we0 = ap_const_logic_0;
    }
}

void pool1::thread_p_shl2_cast_fu_248_p3() {
    p_shl2_cast_fu_248_p3 = esl_concat<9,3>(trunc_ln203_fu_244_p1.read(), ap_const_lv3_0);
}

void pool1::thread_p_shl6_cast_fu_393_p3() {
    p_shl6_cast_fu_393_p3 = esl_concat<11,3>(trunc_ln1494_fu_389_p1.read(), ap_const_lv3_0);
}

void pool1::thread_select_ln61_fu_435_p3() {
    select_ln61_fu_435_p3 = (!icmp_ln1494_fu_429_p2.read()[0].is_01())? sc_lv<16>(): ((icmp_ln1494_fu_429_p2.read()[0].to_bool())? C1_out_V_q0.read(): p_07_2_reg_146.read());
}

void pool1::thread_sext_ln1494_1_fu_409_p1() {
    sext_ln1494_1_fu_409_p1 = esl_sext<14,13>(tmp_9_fu_401_p3.read());
}

void pool1::thread_sext_ln1494_fu_355_p1() {
    sext_ln1494_fu_355_p1 = esl_sext<12,11>(sub_ln1494_fu_349_p2.read());
}

void pool1::thread_sext_ln203_1_fu_264_p1() {
    sext_ln203_1_fu_264_p1 = esl_sext<12,11>(tmp_7_fu_256_p3.read());
}

void pool1::thread_sext_ln203_fu_211_p1() {
    sext_ln203_fu_211_p1 = esl_sext<10,9>(sub_ln203_fu_205_p2.read());
}

void pool1::thread_shl_ln61_1_fu_227_p3() {
    shl_ln61_1_fu_227_p3 = esl_concat<4,1>(j_0_reg_100.read(), ap_const_lv1_0);
}

void pool1::thread_shl_ln_fu_181_p3() {
    shl_ln_fu_181_p3 = esl_concat<4,1>(i_0_reg_89.read(), ap_const_lv1_0);
}

void pool1::thread_sub_ln1494_1_fu_413_p2() {
    sub_ln1494_1_fu_413_p2 = (!p_shl6_cast_fu_393_p3.read().is_01() || !sext_ln1494_1_fu_409_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(p_shl6_cast_fu_393_p3.read()) - sc_bigint<14>(sext_ln1494_1_fu_409_p1.read()));
}

void pool1::thread_sub_ln1494_fu_349_p2() {
    sub_ln1494_fu_349_p2 = (!zext_ln1494_fu_333_p1.read().is_01() || !zext_ln1494_4_fu_345_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(zext_ln1494_fu_333_p1.read()) - sc_biguint<11>(zext_ln1494_4_fu_345_p1.read()));
}

void pool1::thread_sub_ln203_1_fu_268_p2() {
    sub_ln203_1_fu_268_p2 = (!p_shl2_cast_fu_248_p3.read().is_01() || !sext_ln203_1_fu_264_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(p_shl2_cast_fu_248_p3.read()) - sc_bigint<12>(sext_ln203_1_fu_264_p1.read()));
}

void pool1::thread_sub_ln203_fu_205_p2() {
    sub_ln203_fu_205_p2 = (!zext_ln203_fu_197_p1.read().is_01() || !zext_ln203_6_fu_201_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(zext_ln203_fu_197_p1.read()) - sc_biguint<9>(zext_ln203_6_fu_201_p1.read()));
}

void pool1::thread_tmp_1_fu_337_p3() {
    tmp_1_fu_337_p3 = esl_concat<5,2>(add_ln61_fu_320_p2.read(), ap_const_lv2_0);
}

void pool1::thread_tmp_7_fu_256_p3() {
    tmp_7_fu_256_p3 = esl_concat<10,1>(add_ln203_fu_239_p2.read(), ap_const_lv1_0);
}

void pool1::thread_tmp_8_fu_189_p3() {
    tmp_8_fu_189_p3 = esl_concat<4,4>(i_0_reg_89.read(), ap_const_lv4_0);
}

void pool1::thread_tmp_9_fu_401_p3() {
    tmp_9_fu_401_p3 = esl_concat<12,1>(add_ln1494_fu_384_p2.read(), ap_const_lv1_0);
}

void pool1::thread_tmp_s_fu_325_p3() {
    tmp_s_fu_325_p3 = esl_concat<5,5>(add_ln61_fu_320_p2.read(), ap_const_lv5_0);
}

void pool1::thread_trunc_ln1494_fu_389_p1() {
    trunc_ln1494_fu_389_p1 = add_ln1494_fu_384_p2.read().range(11-1, 0);
}

void pool1::thread_trunc_ln203_fu_244_p1() {
    trunc_ln203_fu_244_p1 = add_ln203_fu_239_p2.read().range(9-1, 0);
}

void pool1::thread_x_fu_314_p2() {
    x_fu_314_p2 = (!x_0_reg_135.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(x_0_reg_135.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void pool1::thread_y_fu_369_p2() {
    y_fu_369_p2 = (!y_0_reg_158.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(y_0_reg_158.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void pool1::thread_zext_ln1494_4_fu_345_p1() {
    zext_ln1494_4_fu_345_p1 = esl_zext<11,7>(tmp_1_fu_337_p3.read());
}

void pool1::thread_zext_ln1494_5_fu_380_p1() {
    zext_ln1494_5_fu_380_p1 = esl_zext<12,5>(add_ln61_1_fu_375_p2.read());
}

void pool1::thread_zext_ln1494_6_fu_424_p1() {
    zext_ln1494_6_fu_424_p1 = esl_zext<64,14>(add_ln1494_3_fu_419_p2.read());
}

void pool1::thread_zext_ln1494_fu_333_p1() {
    zext_ln1494_fu_333_p1 = esl_zext<11,10>(tmp_s_fu_325_p3.read());
}

void pool1::thread_zext_ln203_10_fu_299_p1() {
    zext_ln203_10_fu_299_p1 = esl_zext<64,12>(add_ln203_3_fu_294_p2.read());
}

void pool1::thread_zext_ln203_6_fu_201_p1() {
    zext_ln203_6_fu_201_p1 = esl_zext<9,5>(shl_ln_fu_181_p3.read());
}

void pool1::thread_zext_ln203_7_fu_235_p1() {
    zext_ln203_7_fu_235_p1 = esl_zext<10,4>(j_0_reg_100.read());
}

void pool1::thread_zext_ln203_8_fu_286_p1() {
    zext_ln203_8_fu_286_p1 = esl_zext<14,3>(k_0_reg_111.read());
}

void pool1::thread_zext_ln203_9_fu_290_p1() {
    zext_ln203_9_fu_290_p1 = esl_zext<12,3>(k_0_reg_111.read());
}

void pool1::thread_zext_ln203_fu_197_p1() {
    zext_ln203_fu_197_p1 = esl_zext<9,8>(tmp_8_fu_189_p3.read());
}

void pool1::thread_zext_ln57_fu_304_p1() {
    zext_ln57_fu_304_p1 = esl_zext<5,2>(x_0_reg_135.read());
}

void pool1::thread_zext_ln59_fu_359_p1() {
    zext_ln59_fu_359_p1 = esl_zext<5,2>(y_0_reg_158.read());
}

void pool1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln50_fu_169_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln52_fu_215_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln54_fu_274_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(icmp_ln57_fu_308_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(icmp_ln59_fu_363_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        default : 
            ap_NS_fsm = "XXXXXXX";
            break;
    }
}

}

