# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.runs/design_1_lenet_0_3_synth_1/.Xil/Vivado-20264-LAPTOP-A2CPK32I/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z010clg400-2
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ip/design_1_lenet_0_3/hdl/verilog {
      D:/vivado/xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      D:/vivado/xilinx/Vivado/2019.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      D:/vivado/xilinx/Vivado/2019.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ip/design_1_lenet_0_3/hdl/verilog {
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_C1_out_V.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_C2_out_V.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_C3_out_V_0_0.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_Crtl_s_axi.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_fadd_32ns_3bkb.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_FC1_B_V.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_FC1_out_V.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_FC1_W_V.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_FC2_B_V.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_FC2_out_V.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_FC2_W_V.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_fdiv_32ns_3cud.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_fexp_32ns_3eOg.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_fpext_32ns_dEe.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_in_V.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K1_B_V.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K1_W_V_0_0.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K1_W_V_0_1.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K1_W_V_0_2.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K1_W_V_0_3.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K1_W_V_0_4.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K1_W_V_1_0.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K1_W_V_1_1.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K1_W_V_1_2.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K1_W_V_1_3.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K1_W_V_1_4.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K1_W_V_2_0.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K1_W_V_2_1.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K1_W_V_2_2.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K1_W_V_2_3.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K1_W_V_2_4.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K1_W_V_3_0.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K1_W_V_3_1.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K1_W_V_3_2.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K1_W_V_3_3.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K1_W_V_3_4.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K1_W_V_4_0.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K1_W_V_4_1.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K1_W_V_4_2.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K1_W_V_4_3.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K1_W_V_4_4.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K1_W_V_5_0.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K1_W_V_5_1.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K1_W_V_5_2.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K1_W_V_5_3.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K1_W_V_5_4.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_0_0.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_0_1.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_0_2.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_0_3.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_0_4.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_0_5.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_1_0.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_1_1.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_1_2.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_1_3.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_1_4.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_1_5.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_2_0.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_2_1.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_2_2.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_2_3.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_2_4.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_2_5.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_3_0.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_3_1.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_3_2.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_3_3.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_3_4.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_3_5.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_4_0.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_4_1.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_4_2.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_4_3.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_4_4.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_4_5.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_5_0.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_5_1.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_5_2.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_5_3.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_5_4.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_5_5.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_6_0.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_6_1.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_6_2.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_6_3.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_6_4.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_6_5.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_7_0.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_7_1.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_7_2.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_7_3.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_7_4.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_7_5.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_8_0.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_8_1.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_8_2.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_8_3.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_8_4.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_8_5.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_9_0.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_9_1.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_9_2.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_9_3.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_9_4.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_9_5.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_10_0.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_10_1.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_10_2.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_10_3.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_10_4.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_10_5.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_11_0.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_11_1.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_11_2.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_11_3.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_11_4.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_11_5.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_12_0.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_12_1.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_12_2.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_12_3.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_12_4.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_12_5.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_13_0.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_13_1.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_13_2.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_13_3.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_13_4.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_13_5.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_14_0.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_14_1.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_14_2.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_14_3.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_14_4.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_14_5.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_15_0.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_15_1.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_15_2.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_15_3.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_15_4.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K2_W_V_15_5.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K3_B_V.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K3_W_V_0.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K3_W_V_1.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K3_W_V_2.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K3_W_V_3.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K3_W_V_4.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K3_W_V_5.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K3_W_V_6.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K3_W_V_7.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K3_W_V_8.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K3_W_V_9.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K3_W_V_10.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K3_W_V_11.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K3_W_V_12.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K3_W_V_13.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K3_W_V_14.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_K3_W_V_15.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_P1_out_V.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet_P2_out_V.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/verilog/lenet.v
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ip/design_1_lenet_0_3/synth/design_1_lenet_0_3.v
    }
      rt::read_vhdl -lib xbip_utils_v3_0_10 d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/1123/hdl/xbip_utils_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib axi_utils_v2_0_6 d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/1971/hdl/axi_utils_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_pipe_v3_0_6 d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/7468/hdl/xbip_pipe_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_wrapper_v3_0_4 d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_addsub_v3_0_6 d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/910d/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_multadd_v3_0_6 d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/b0ac/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_bram18k_v3_0_6 d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/d367/hdl/xbip_bram18k_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib mult_gen_v12_0_15 d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/d4d2/hdl/mult_gen_v12_0_vh_rfs.vhd
      rt::read_vhdl -lib floating_point_v7_1_8 d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/83a3/hdl/floating_point_v7_1_vh_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib {
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/ip/lenet_ap_fadd_2_full_dsp_32.vhd
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/ip/lenet_ap_fdiv_10_no_dsp_32.vhd
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/ip/lenet_ap_fexp_6_full_dsp_32.vhd
      d:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.srcs/sources_1/bd/design_1/ipshared/a85b/hdl/ip/lenet_ap_fpext_0_no_dsp_32.vhd
    }
      rt::read_vhdl -lib xpm D:/vivado/xilinx/Vivado/2019.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList D:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.runs/design_1_lenet_0_3_synth_1/.Xil/Vivado-20264-LAPTOP-A2CPK32I/realtime/design_1_lenet_0_3_synth.xdc
    rt::sdcChecksum
    set rt::top design_1_lenet_0_3
    rt::set_parameter enableIncremental true
    set rt::ioInsertion false
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: out_of_context
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "D:/FPGA_project/lenet_7010/lenet_v_p/lenet_v_p.runs/design_1_lenet_0_3_synth_1/.Xil/Vivado-20264-LAPTOP-A2CPK32I/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
